woowacourse/prolog

- frontend/src/pages/PostPage/index.js
- frontend/src/pages/PostPage/styles.js
- post page 화면에서 markdown이 파싱된 채로 출력되는 기능 추가
> feat: post page markdown parser 적용

- frontend/src/pages/ProfilePage/index.js
- frontend/src/pages/ProfilePagePosts/index.js
버그 목록
1. 다른 사람 프로필 페이지에서 내 프로필 페이지로 이동 시, 알맞은 프로필이 뜨도록 수정
2. 프로필 페이지 내에서, content tab과 content 내용이 올바르게 매칭되지 않는 버그 수정
3. 내가 쓴 글 목록에서 글 클릭시 해당 글 상세페이지로 갈 때, 클릭 영역 수정
> fix: 프로필 페이지 관련 버그 픽스

- frontend/src/pages/PostPage/styles.js
Post Page 내용 폰트 크기 13px에서 16px로 변경
> refactor: Post Page 내용 폰트 크기 13px에서 16px로 변경

- frontend/src/components/SelectBox/SelectBox.js
- frontend/src/components/SelectBox/SelectBox.styles.js
- frontend/src/hooks/useCustomSelectBox.js
- frontend/src/hooks/useScrollToSelected.js
- frontend/src/pages/EditPostPage/index.js
- frontend/src/pages/NewPostPage/index.js
resolved #254 
리포트 목록을 불러올때도 SelectBox를 사용할 것 같아서 리팩토링을 진행했습니다.
- 기존의 customSelectBox가 안보이는 상황 (ex. 스크린리더)에서는 선택을 해도 반영이 되지 않아서 이 부분도 함께 수정했습니다.
- customSelectBox의 전체 너비와 높이를 받아서 사용할 수 있도록 수정했습니다.
- label의 이름이 없어서, title(aria-label)도 컴포넌트를 사용하는 쪽에서 입력하도록 수정하였습니다.
- 로직이 너무 길어지는 것 같아서 hook으로 스크롤 위치 찾아가는 것과 selectbox를 여닫을 수 있게 분리하였습니다.
- 에디터창과 드롭다운 메뉴가 겹치는 오류를 해결하였습니다.
> refactor: SelectBox 컴포넌트 리팩토링

- backend/src/acceptanceTest/resources/application.yml
- backend/src/acceptanceTest/resources/logback-spring.xml
- backend/src/acceptanceTest/resources/logback/console-logger.xml
- backend/src/main/java/wooteco/prolog/common/exception/ExceptionController.java
- backend/src/main/java/wooteco/prolog/common/exception/ExceptionDto.java
- backend/src/main/resources/application-local.yml
- backend/src/main/resources/application-test.yml
- backend/src/main/resources/logback-access.xml
- backend/src/main/resources/logback-spring.xml
- backend/src/main/resources/logback/access-logger.xml
- backend/src/main/resources/logback/console-access-logger.xml
- backend/src/main/resources/logback/console-logger.xml
- backend/src/main/resources/logback/debug-logger.xml
- backend/src/main/resources/logback/error-logger.xml
- backend/src/main/resources/logback/info-logger.xml
- backend/src/main/resources/logback/warn-logger.xml
- **프로덕션(wooteco.prolog)**
- ERROR Level 로깅 (콘솔, 파일)
- **스프링 프레임워크(org.springframwork)**
- INFO Level 로깅 (콘솔, 파일)
- **프로덕션(wooteco.prolog)**
- DEBUG Level 로깅 (콘솔, 파일)
- **스프링 프레임워크(org.springframwork)**
- INFO Level 로깅 (콘솔, 파일)
- **프로덕션(wooteco.prolog)**
- DEBUG Level 로깅 (콘솔)
- **스프링 프레임워크(org.springframwork)**
- INFO Level 로깅 (콘솔)
- **SQL 출력(org.hibernate,SQL)**
- DEBUG Level 로깅 (콘솔)
- **Binding parameter (org.hibernate.type.descriptor.sql.BasicBinder)**
- TRACE Level 로깅 (콘솔)
- **Select result (org.hibernate.type.descriptor.sql.BasicExtractor)**
- TRACE Level 로깅 (콘솔)
```
access  debug   error   info    warn
```
- 시간 및 로그 파일 크기 기반
- 15MB 
- 7일
```
public class ExceptionController {
@ExceptionHandler(BadRequestException.class)
public ResponseEntity<ExceptionDto> …
```
> 백엔드 로깅을 도입한다.

- frontend/src/components/Card/EditPostCard.js
- frontend/src/components/Card/NewPostCard.styles.js
closes #296 
height가 너무 낮게 설정되어 있어서 발생한 버그였습니다. 글 수정 페이지와 같게 유지해 버그를 수정했습니다.
(사파리에서 테스트는 못해봤는데 이슈는 없을 것 같습니다.)
그리고 글 수정 페이지에서 require같은 속성이 글 추가 페이지와 달라서 동일하게 유지시켰습니다.
> fix: 글 추가 페이지에서 제목이 잘리는 버그 수정

- backend/src/main/java/wooteco/prolog/studylog/application/dto/search/SearchArgumentResolver.java
- frontend/src/hooks/useFilterWithParams.js
- frontend/src/pages/MainPage/index.js
- frontend/src/pages/ProfilePagePosts/index.js
- #377 
- 사이즈와 정렬은 쿼리 스트링에서 제거한다
- 첫 페이지 시 page=1 쿼리 스트링을 제거한다.
- 필터를 제거했을 때 첫 페이지로 이동한다
- 프로필 > 포스트usernames를 쿼리스트링에서 제거한다.
> 학습로그 목록 조회 시 필요한 쿼리 스트링 변경

- frontend/src/hooks/useFilterWithParams.js
- frontend/src/pages/ProfilePagePosts/index.js
연관 이슈
- 2 > 1 페이지 이동 x
- 마지막 필터 취소 시 취소되지 않음
> fix: 필터 및 페이징이 정상동작하지 않는 이슈 해결

- frontend/src/pages/ProfilePage/index.js
- frontend/src/service/requests.js
#394 
태그/ 달력을 선택했을 때 이전 페이지가 그대로 전달되고 있어서 생긴 버그였습니다.
해결 완료!
> 오버뷰 페이지에서 태그/달력 선택 시 페이지 초기화가 되지 않는 버그 수정

- frontend/src/components/ProfilePageSideBar/ProfilePageSideBar.js
다른 사람의 닉네임도 수정할 수 있는 버그를 발견해 해결했습니다.
이제는 자신의 프로필이 아니라면 수정 버튼이 보이지 않습니다.
> 다른 사람의 닉네임을 수정할 수 있는 버그 해결

- backend/src/main/java/wooteco/prolog/DataLoaderApplicationListener.java
- backend/src/main/java/wooteco/prolog/login/aop/LoginMemberVerifier.java
- backend/src/main/java/wooteco/prolog/login/aop/MemberOnly.java
- backend/src/main/java/wooteco/prolog/login/aop/OnlyMember.java
- backend/src/main/java/wooteco/prolog/login/ui/AuthMemberPrincipalArgumentResolver.java
- backend/src/main/java/wooteco/prolog/login/ui/LoginMember.java
- backend/src/main/java/wooteco/prolog/member/application/MemberService.java
- backend/src/main/java/wooteco/prolog/member/ui/MemberController.java
- backend/src/main/java/wooteco/prolog/studylog/application/StudylogService.java
- backend/src/main/java/wooteco/prolog/studylog/ui/StudylogController.java
- backend/src/test/java/wooteco/prolog/member/application/MemberServiceTest.java
- backend/src/test/java/wooteco/prolog/posttag/application/StudylogTagServiceTest.java
- backend/src/test/java/wooteco/prolog/studylog/studylog/application/StudylogServiceTest.java
- backend/src/test/java/wooteco/prolog/studylog/studylog/util/StudylogUtilCRUD.java
- backend/src/test/java/wooteco/prolog/studylog/studylogtag/application/StudylogTagServiceTest.java
변경 전, ArgumentResolver 에서 직접적으로 MemberService를 호출해 Member 도메인을 완성하는 과정이었습니다!
변경 후, ArgumentResolver는 Token 값만 확인해 유효한 토큰이 존재한다면 Member 권한을 갖고 유효한 토큰이 아니거나 존재하지 않다면 Anonymous 권한을 갖게끔 설계했습니다. 
여기서 사용되는 DTO 명은 `LoginMember` 로 만들었습니다!
그리고 AOP를 이용해 `@OnlyMember`가 붙어있는 api 는 무조건 Member 권한이어야만 호출될 수 있게끔 만들었습니다!
(#414 이슈에서 분기 처리가 필요한 부분도 필요하기에 `@OnlyMember` 를 사용하지 않는다면 분기 처리로 해결할 수 있습니다!)
> refactor: ArgumentResolver 에서 서비스 직접 참조 끊고 LoginMember Dto 로 변환

- backend/src/acceptanceTest/java/wooteco/prolog/AcceptanceContext.java
- backend/src/acceptanceTest/java/wooteco/prolog/steps/LoginStepDefinitions.java
- backend/src/acceptanceTest/java/wooteco/prolog/steps/MemberStepDefinitions.java
- backend/src/documentation/java/wooteco/prolog/docu/LoginDocumentation.java
- backend/src/documentation/java/wooteco/prolog/docu/MemberDocumentation.java
- backend/src/main/java/wooteco/prolog/member/application/MemberService.java
- backend/src/main/java/wooteco/prolog/member/ui/MemberController.java
- backend/src/test/java/wooteco/prolog/member/application/MemberServiceTest.java
기존의 me로 동작하던 API들이 정상적으로 동작할 수 있도록 남겨두고 Deprecate시켜놨습니다. 프론트측에서 수정이 완료시 Deprecate된 메서드를 제거할 예정입니다.
추가적으로 Acceptacne context쪽에 storage Map을 추가했습니다. 각 step마다 데이터 공유가 불편해서 추가하였고 이를 통해서 인수테스트 작성에 조금 더 편해질것으로 예상합니다.
resolve #258
> [ #258] /member/me 를 [GET, PUT] /member/{username} 으로 변경한다.

- frontend/src/pages/ProfilePageNewReport/index.js
- 리포트 title에서 양 끝에 공백을 제거하는 `trim()` 메소드 추가
> fix: 리포트 제목 문자열 양 끝 공백 제거

- backend/src/main/java/wooteco/prolog/login/application/JwtTokenProvider.java
- backend/src/test/java/wooteco/prolog/login/application/JwtTokenProviderTest.java
resolve #477 
존맛탱 토큰이 만료되거나 기타 유효하지 않은 토큰일 시, Runtime Exception이 아닌 적합한 예외코드를 반환하도록 수정하였습니다. 정확한 예외 발생지점을 확인할 수 없어 배포 후 확인이 필요합니다.
> feat: 적합하지 않은 JWT 토큰 parsing 시 예외를 catch하는 로직 추가

- frontend/src/pages/EditPostPage/index.js
학습로그 수정 시 글이 불러와 지지 않는 이슈 해결했습니다.
- editPage에서 기존 데이터 요청 시 파라미터 오류 있었음.
- getPost 시 accessToken 여부에 대해서 논의 필요할 듯.
> hotfix: 학습로그 수정시 글이 불러와 지지 않는 이슈 해결

- frontend/src/pages/EditPostPage/index.js
- editPage에서 기존 데이터 요청 시 파라미터 오류 있었음.
- getPost 시 accessToken 여부에 대해서 논의 필요할 듯.
> fix: 학습로그 수정시 글이 불러와 지지 않는 이슈 해결 (#498)

- backend/src/acceptanceTest/java/wooteco/prolog/steps/ReportStepDefinitions.java
- backend/src/main/java/wooteco/prolog/report/domain/report/abilitygraph/GraphAbility.java
리포트 업데이트가 안되는 버그를 확인하였습니다.
확인 결과 업데이트 안되는 필드의 업데이트로직 누락을 확인하였습니다.
위와 같이 로직 추가하였습니다.
close #504
> [#504] 리포트 수정기능 버그를 확인한다. 

- search/mapping-index-and-sync/HELP.md
- search/mapping-index-and-sync/mapping-index-and-sync.sh
close #521 
엘라스틱 서치 index mapping에 사용되는 내용이 closed issue에만 작성되어있어 레포지토리에 포함했습니다.
특히, index mapping 후에는 RDB와의 sync 작업이 필요한데 둘 모두를 동시에 실행할 수 있도록 하기 위해 쉘 스크립트의 형태로 작성했습니다.
실행 방법은 HELP.md에 명시해두었습니다.
> [검색] elasticsearch index mapping을 코드에 포함한다.

- backend/src/acceptanceTest/java/wooteco/prolog/steps/ReportStepDefinitions.java
- backend/src/main/java/wooteco/prolog/report/application/dto/report/ReportAssembler.java
- backend/src/main/java/wooteco/prolog/report/domain/report/abilitygraph/GraphAbilities.java
- backend/src/main/java/wooteco/prolog/report/domain/report/abilitygraph/datastructure/GraphAbilityDto.java
- backend/src/test/java/wooteco/prolog/common/fixture/ability/AbilityFixture.java
- backend/src/test/java/wooteco/prolog/studylog/application/ReportServiceTest.java
- backend/src/test/java/wooteco/prolog/studylog/domain/repository/ReportRepositoryTest.java
- backend/src/test/resources/jsons/report_post_request.json
- backend/src/test/resources/jsons/report_post_response.json
- backend/src/test/resources/jsons/report_put_response.json
(색, 상위하위) 로 정렬되도록 하였습니다.
close #508
> [리포트] 리포트의 학습로그 역량을 부모-자식으로 정렬하여 반환한다.  #508

- frontend/src/hooks/useRequest.js
- frontend/src/pages/ProfilePageReports/index.js
- frontend/src/pages/ProfilePageReportsList/index.tsx
fix #541 
* 기존 reports API 응답 형태가
* response: [ report ...] 에서
* response: { reports: [report...], page: 0, ...]
* 으로 변화함에 따라 데이터를 이용하는 과정에서 이슈가 생겨 해당부분 수정했습니다.
> fix: API 변경에 따른 데이터 응답구조 처리 부분 에러 처리

- frontend/src/components/NavBar/NavBar.js
- frontend/src/constants/api.js
- frontend/src/hooks/useRequest.js
- frontend/src/pages/ProfilePageReports/index.js
- frontend/src/pages/ProfilePageReportsList/index.tsx
- frontend/src/redux/actions/userAction.js
fix #513 
토큰 만료 및 유효하지 않을 시 gnb 영역의 상태가 변하지 않는 이슈를 수정하였습니다.
해당 부분은 초기 api 에서 유효하지 않은 상태의 jwt일 때 api error code를 500으로 받아서 분기 처리를 하는 부분에서 발생한 이슈로, 해당 부분을 !response.ok 로 처리하였고, api.js 문서의 상태코드를 수정해두었습니다
> fix: 토큰 만료 및 유효하지 않을 시 gnb 영역의 상태가 변하지 않는 이슈 수정

- frontend/src/components/Chip/Chip.js
- frontend/src/components/Chip/Chip.styles.js
- frontend/src/pages/ProfilePageEditReport/index.js
- frontend/src/pages/ProfilePageNewReport/ReportStudyLogTable.js
- frontend/src/pages/ProfilePageNewReport/ReportStudyLogTable.styles.js
- frontend/src/pages/ProfilePageNewReport/index.js
- frontend/src/pages/ProfilePageReports/ReportStudyLogTable.js
- frontend/src/pages/ProfilePageReports/ReportStudyLogTable.styles.js
related #247 
보완이 필요한 부분
---
디자인이 저번에 이야기 했을 때, 바뀔 수도 있다고해서 현재는 간략하게만 만들었습니다.
리포트 수정, 등록, 조회에서 모두 해당하는 학습로그의 역량을 확인할 수 있습니다.
1. 사용자가 리포트를 생성한다.
2. 사용자는 자신의 역량을 리포트 생성 페이지에서 확인할 수 있고, 현재 리포트에서 `등록할 역량을 체크`할 수 있다.
3. 사용자는 학습로그를 `학습로그 목록`에 추가한다.
4. 학습로그에는 `2에서 선택한 역량만 선택할 수 있다.` => 현재 화면에 그려주고 있지 않음.
https://user-images.githubusercontent.com/59258239/139670770-edabb19b-7697-48b0-a4e3-61f36d1acb11.mov
> feat: 리포트 학습로그 목록에 역량을 추가한다.

- backend/src/main/java/wooteco/prolog/login/aop/LoginMemberVerifier.java
- backend/src/main/java/wooteco/prolog/login/aop/MemberAuthorityCache.java
- backend/src/main/java/wooteco/prolog/login/ui/AuthMemberPrincipalArgumentResolver.java
빈 스코프(`Request`)를 이용해 `@MemberOnly` 어노테이션을 사용해도 `LoginMember`를 안 넣어도 될 수 있게끔 수정한다.
1. 가지고 있는 `WebRequest` 정보를 가져와 다시 토큰의 페이로드를 분석한다 
-> 두 번의 토큰 확인 작업이 이뤄나서 패스!
2. `LoginMember` 자체를 `Request` 스코프 빈으로 지정해 해결한다.
-> 스코프를 따로 주어 사용 시 프록시를 이용하게 되는데 getter 와 같이 값을 가져와야지만 내부 값을 읽을 수 있게됨. 즉, 내부에서 값을 
비교 시 비어있기에 올바른 비교가 힘듬. 예를 들어, `LoginMember.isMember()` 는 내부에서 값을 비교하기에 계속 `false`. 
getter 를 이용해 해결할 수 있지만 다른 곳에서도 계속 이런 조심을 해야하기에 패스!
3. `LoginMember` 와 관련 없는 `MemberAuthorityCache` 로 관리. -> 채택
다른 아이디어 있으신다면 언제든 이야기해주세요~!!
> refactor: @MemberOnly 에 LoginMember 없어도 되게끔 수정

- frontend/src/components/Lists/StudyLogList.tsx
- frontend/src/components/NavBar/NavBar.js
- frontend/src/components/ProfilePageSideBar/ProfilePageSideBar.js
- frontend/src/pages/AbilityPage/index.js
- frontend/src/pages/LoginCallbackPage/index.js
- frontend/src/pages/MainPage/index.js
- frontend/src/pages/PostPage/index.js
- frontend/src/pages/ProfilePage/index.js
- frontend/src/pages/ProfilePageReports/index.js
기존의 yarn의 문제점인 유령 의존성으로 인해서, `react-router-dom` 라이브러리의 API를 사용할 때 자동으로 react-router가 import 된 부분이 있어서 수정하였습니다.
> fix: Phantom Dependency으로 인한 오류 해결

- backend/src/main/resources/application-local.yml
- backend/src/main/resources/application-test.yml
ref: https://stackoverflow.com/questions/48553706/elasticsearch-health-check-failed-every-time-when-spring-boot-start-up
> feat: elasticsearch auto healthcheck 비활성화

- backend/src/main/java/wooteco/prolog/report/application/HistoryAbilityService.java
- backend/src/main/java/wooteco/prolog/report/domain/ablity/StudylogAbility.java
- backend/src/main/java/wooteco/prolog/report/domain/ablity/Studylogs.java
- backend/src/main/java/wooteco/prolog/report/domain/report/repository/StudylogAbilityRepository.java
해결은 했습니다만 뚜렷한 이유는 모르겠습니다.
일단 연관관계 주인 관련된 셋팅이 잘 안돼있던 부분이 발견돼서 처리하였습니다(join_column 및 mappedBy 누락)
studylog를 불러오지 못하는(null) 버그는
기본 생성자에 ArrayList<>()를 바인딩 해서 해결했는데, 이게 왜 기본적으로 있어야 하는지 잘 이해가 안되네요..
안넣어줘도 잘 됐던것 같은데... 오묘한 JPA의 세계....
> [역량] 스터디로그-역량 매핑 데이터를 불러오지 못하는 버그를 해결한다.

- backend/src/main/java/wooteco/prolog/studylog/application/StudylogService.java
- backend/src/main/java/wooteco/prolog/studylog/domain/repository/StudylogReadRepository.java
- backend/src/main/java/wooteco/prolog/studylog/domain/repository/StudylogScrapRepository.java
- backend/src/main/java/wooteco/prolog/studylog/exception/StudylogReadNotExistException.java
- backend/src/main/java/wooteco/prolog/studylog/exception/StudylogScrapAlreadyRegisteredException.java
- backend/src/main/java/wooteco/prolog/studylog/exception/StudylogScrapNotExistException.java
- backend/src/main/java/wooteco/prolog/studylog/exception/StudylogScrapNotValidUserException.java
- studylog 삭제 시 해당 글에 대한 스크랩과 읽음여부도 같이 삭제되도록 수정했습니다.
Close #634
> fix: studylog 삭제가 안되는 오류 수정

- backend/src/main/java/wooteco/prolog/studylog/domain/Like.java
- backend/src/main/java/wooteco/prolog/studylog/domain/Likes.java
- backend/src/main/java/wooteco/prolog/studylog/domain/Studylog.java
- backend/src/main/java/wooteco/prolog/studylog/ui/StudylogLikeController.java
에러로그는 JPA 롤백이지만 자세한 trace를 확인할 수 없어 우선 발견한 버그 가능 지점만 수정합니다.
- StudylogLikeController 에 uri path 에 `/` 누락된 부분
- 발생하고 있는 에러  `Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Error while committing the transaction` 
- 정확히 왜 이런 에러가 발생하는지 디버깅을 할 수 없고 stack trace가 남지 않는 관계로 유추할 수밖에 없는 상황인데요 ㅠㅠ 
- 에러가 발생할 수 있는 예상 지점은 1) Flyway 혹은 2) 알 수 없는 JPA 연관관계 문제 라고 생각합니다. 
- 1)번 같은 경우에는 ddl-auto 설정이  validate 이므로 문제가 될 여지가 적다고 생각
- **2)번은 현재 일대다 단방향 연관관계를 사용하고 있었으나 매우 비추하는 연관관계이므로 다대일 양방향으로 수정**
- 문제가 된 부분은 아니라고 생각하지만 entity의 필드는 final이 아닌것이 원칙이므로 Likes 내부 values 컬렉션에 final을 제거 
resolve #684
> [좋아요 버그] dev 서버 에러 발생 

- frontend/src/contexts/UserProvider.js
- frontend/src/pages/LoginCallbackPage/index.js
*   로그인 성공 시 상태 업데이트를 하고 있지 않은 이슈 수정
*   accessToken 변경시 Members/me 재 요청 보내도록 수정
*   accessToken 값이 Null 일 시 members/me 요청을 보내지 않도록 수정
*   깃허브에 직접 Id, pw 를 입력하는 경우 history.goBack() 을 이용하면 이전 조회하던 페이지가 유지되지 않는 이슈로, 로그인 성공시 무조건 메인화면으로 가도록 수정
> fix: 로그인 상태 이상을 해결한다.

- frontend/src/constants/message.js
- frontend/src/pages/StudylogPage/index.js
* 학습로그 삭제 시 학습로그 페이지로 라우팅
* 학습로그 삭제 완료 시 안내메세지 노출
* 그 외 이슈는 백엔드 확인 필요함
> hotfix(FE): 학습로그 삭제시 라우트 및 성공 메세지가 노출되지 않는 이슈 해결

- frontend/src/hooks/useStudylog.js
- frontend/src/pages/MainPage/index.js
fixed #712 
해당 이슈 글 불러오기 시 unauthorization Error 에 대한 추가 대응이 없어 발생한 이슈로, 추후 공통된 에러 처리 로직 추가(#713)가 필요합니다.
로컬에서 재현시 store에 저장된 값을 임의로 유효하지 않은 값으로 만들기 위해
MainPage 코드 의 다음 코드를 아래와 같이 수정하여 임의로 확인 가능합니다.
```
useEffect(() => {
fetchRecentStudylogs({ query: { type: 'searchParams', data: 'size=3' }, accessToken });
}, [accessToken]);
```
```
useEffect(() => {
fetchRecentStudylogs({ query: { type: 'searchParams', data: 'size=3' }, accessToken: accessToken ? accessToken + '1' : accessToken});
}, [accessToken]);
```
> hotfix: 로그인 세션이 만료되었을때 홈화면에 글 리스트가 나오지 않는 이슈 수정

- backend/build.gradle
- backend/src/documentation/adoc/ability.adoc
- backend/src/documentation/adoc/index.adoc
- backend/src/documentation/adoc/level.adoc
- backend/src/documentation/adoc/login.adoc
- backend/src/documentation/adoc/profile.adoc
- backend/src/documentation/adoc/reaction.adoc
- backend/src/documentation/adoc/studylog.adoc
- backend/src/documentation/adoc/studylogOverview.adoc
- backend/src/documentation/java/wooteco/prolog/docu/LevelDocumentation.java
- backend/src/documentation/java/wooteco/prolog/docu/MemberDocumentation.java
- backend/src/documentation/java/wooteco/prolog/docu/ProfileDocumentation.java
- backend/src/documentation/java/wooteco/prolog/docu/StudylogDocumentation.java
- backend/src/documentation/java/wooteco/prolog/docu/StudylogOverviewDocumentation.java
- backend/src/main/java/wooteco/prolog/studylog/ui/ProfileStudylogController.java
- 누락되어 있는 API를 찾아 추가했습니다. 
- 엘서 관련 테스트가 간혹 깨져서 안정화되기 이전까지 주석처리 했습니다. 
- 누군가 build.gradle에 restdocs 스크립트를 주석처리해서 해제했습니다. (문서가 최신화 되지 않았던 이유) 
- posts -> studylogs로 변경하여 이전내용에 deprecated 된 것들이 코드와 문서에 혼재되어 있어 한번 정리해야할 것 같습니다. 
- 현재는 @deprecated 어노테이션으로 구분 중인데 가독성이 좋은 것 같지는 않습니다. 
- scrap 관련 API가 어색한 것 같아서 이슈등록 했습니다. #750 
resolves #708
> [API 문서 개선] 최신화

- frontend/src/contexts/UserProvider.js
resolve #744 
* 오류에 대한 설명은 이슈에 설명되어 있으므로 생략
* 코드 수정
* localStorage에 저장되어있는 accessToken을 가져오는 것이 utils 함수로 어디에서나 사용할 수 있기 때문에 바로 default 값에 넣어도 될 것이라고 생각합니다. 어차피 그때 값이 없다면 null이 리턴되므로 기존에 있었던 코드의 기존값과 같아집니다. 또한, 처음 렌더시 state에 초기값을 넣는데 또 useEffect로 accessToken에 대한 상태값을 바꿔주는 것이 useState의 default value를 넣어주는 것과 동일한 작업을 두번 반복한다는 생각이 들어서 삭제하였습니다. 
* 문제 발생이 역량 페이지처럼 특수한 페이지 내에서만 나는 걸로 봐서, 다음 배포때 나가도 될 것 같은데 
만약 다른 페이지에서 비슷한 문제가 있다면 핫픽스로 나가야할 것 같습니다. 일단 버그로 올리겠습니다.
> fix: userContext의 DEFAULT_USER 수정 및 불필요한 useEffect 삭제

- backend/src/main/java/wooteco/prolog/studylog/application/StudylogService.java
- backend/src/main/java/wooteco/prolog/studylog/application/dto/StudylogResponse.java
- backend/src/main/java/wooteco/prolog/studylog/application/dto/StudylogTempResponse.java
- backend/src/main/java/wooteco/prolog/studylog/domain/Studylog.java
- backend/src/main/java/wooteco/prolog/studylog/domain/StudylogTags.java
- backend/src/main/java/wooteco/prolog/studylog/domain/StudylogTemp.java
- backend/src/main/java/wooteco/prolog/studylog/domain/StudylogTempTag.java
- backend/src/main/java/wooteco/prolog/studylog/domain/StudylogTempTags.java
- backend/src/main/resources/db/migration/prod/V24__add_session_column_to_studylogtemp.sql
- backend/src/main/resources/db/migration/prod/V25__create_studylogtemptag_table.sql
- backend/src/test/java/wooteco/prolog/studylog/studylog/domain/TitleTest.java
> fix: 임시저장 관련 버그 수정

- frontend/src/components/Items/PopularStudylogItem.tsx
- frontend/src/pages/MainPage/PopularStudyLogList.tsx
- frontend/src/pages/MainPage/styles.ts
> refactor: 인기 학습 로그 카드에서 scrollbar 숨김 처리

- backend/src/main/java/wooteco/prolog/ability/domain/Ability.java
- backend/src/test/java/wooteco/prolog/report/domain/ablity/AbilityTest.java
일부 크루들이 학습로그와 역량을 매핑하려고 할 때 오류가 발생하였다.
해당 오류를 수정하여 모든 크루들이 학습로그와 역량을 매핑시킬 수 있다.
> feat: 학습로그와 역량 매핑 오류 수정

- backend/src/main/java/wooteco/prolog/studylog/domain/repository/CommentRepository.java
- backend/src/test/java/wooteco/prolog/studylog/domain/repository/CommentRepositoryTest.java
* #953 PR의 버그 수정
* 댓글의 `isDelete`가 `true`여도 댓글이 조회되는 문제를 수정
> fix: isDelete가 true일 경우 댓글이 조회되지 않도록 수정

- frontend/src/components/Comment/Comment.tsx
API 명세가 `YYYY-MM-DD` 형식으로 하기로 했다가, `YYYY-MM-DD hh-mm-ss` 형식으로 변경하기로 했습니다.
그에 따라 날짜 형식을 수정했습니다.
게시물에서 보이는 형식과 같이 `2022. 9. 4. 오후 4:51:54` 처럼 보여줍니다.
빠른 시일 내에, `5분 전`, `10시간 전`, `4일 전` 형식으로 표현하고자 합니다.
[이슈](https://github.com/woowacourse/prolog/issues/1001) 파두었습니다.
> fix: 댓글 작성 날짜 형식 수정

- frontend/src/components/Editor/SideBar/StudyLogSelectAbilityBox.js
- frontend/src/pages/MainPage/styles.ts
- 역량관리페이지 이동 링크를 새 탭에서 열기
- 학습로그 작성 도중 역량관리페이지 이동 링크를 눌러서 작성 중인 글을 잃지 않도록 새 탭으로 열도록 변경한다
- 인기있는 학습로그 아이템 높이 증가
- 인기있는 학습로그 아이템에 마우스를 올리면 살짝 올라오는데, 현재 상단이 약간 잘리므로, 여유있게 높이를 증가한다
> chore: 링크 새 탭에서 열기 및 인기있는 학습로그 높이 증가

- frontend/src/pages/ProfilePageStudylogs/index.js
내 학습로그 페이지에 들어가면 뒤로가기를 3번해야 1번 제대로 작동하는 버그
history 객체의 location.pathname 속성을 활용하여 history.push 메서드가 한 번만 실행되도록 변경하였습니다.
내 학습로그 페이지에 접속하면 1번 렌더링 + 2번의 리렌더링이 연속적으로 (아무런 상호작용을 하지 않아도) 발생되는 근본적인 문제에 대한 해결이 추후에 필요해보입니다.
Close #828
> fix: 내 학습로그에서 뒤로가기를 3번해야 작동하는 문제 해결

- frontend/src/components/Editor/Editor.tsx
- frontend/src/hooks/useImage.ts
- frontend/src/service/requests.js
구현 기능
> 프롤로그 작성시 사진을 넣는 경우 base64로 인코딩되어 url이 길어지는 문제 발생
- 사진이 업로드 되면 해당 파일을 /images로 전송한 후 서버에서 s3에 등록후 해당 url을 받아 이를 렌더링하는 형식으로 변경
주의 사항
- 현재 로컬에서 테스트가 불가한 상황이라 데브에서 테스트를 위해 PR작성합니다.
> feat: 이미지 삽입 기능

- frontend/.storybook/main.js
- frontend/src/components/Button/ResponsiveButton.stories.js
- frontend/src/components/Button/ResponsiveButton.tsx
- frontend/src/components/KeywordSection/KeywordSection.stories.js
- frontend/src/components/KeywordSection/KeywordSection.tsx
- frontend/src/components/LabelledImage/LabelledImage.stories.js
- frontend/src/components/LabelledImage/LabelledImage.tsx
- API 명세가 도출되기 전까지, storybook을 활용하여 하위 컴포넌트를 구성해놓습니다.
**ResponsiveButton**
아무래도 기존 Button 컴포넌트로는 재사용이 불가능하고, 각 size마다 rem을 명시해놓아서, 반응형이 어려울 것 같았습니다. 이 컴포넌트는 무조건 width 100%를 가집니다. 상위에서 ResponsiveButton을 감싸서 반응형 크기를 조절합니다. 
이름은... Button이 이미 있어서 다르게 지어보았습니다만, 괜찮은지 리뷰 부탁드립니다.
**LaballedImage**
**KeywordSection**
Resolves #1046
> feat: 로드맵을 위한 하위 컴포넌트 구현

- frontend/public/index.html
- frontend/src/components/@shared/SideSheet/SideSheet.stories.tsx
- frontend/src/components/@shared/SideSheet/SideSheet.style.ts
- frontend/src/components/@shared/SideSheet/SideSheet.tsx
close #1046 
- 로드맵을 위한 하위 컴포넌트로서 사이드시트 모달을 구현하고 해당 컴포넌트의 스토리북을 작성함
- 사용방법
```typescript
const Component = () => {
const [isSideSheetOpen, setIsSideSheetOpen] = useState(false);
const handleOpenSideSheet = () => {
setIsSideSheetOpen(true);
};
const handleCloseSideSheet = () => {
setIsSideSheetOpen(false);
};
return (
<>
<button onClick={handleOpenSideSheet}>
로드맵 열기
</Button>
{isSideSheetOpen && (
<SideSheet
handleCloseSideSheet={handleCloseSideSheet}
><넣을 컴포넌트>  
</SideSheet>
)}
</>
)
}
```
> feat: 로드맵을 위한 하위 컴포넌트 구현(sidesheet modal)

- frontend/src/components/Editor/Editor.tsx
- frontend/src/hooks/useImage.ts
- frontend/src/service/requests.js
프롤로그 작성시 사진을 넣는 경우 base64로 인코딩되어 url이 길어지는 문제 발생
사진이 업로드 되면 해당 파일을 /images로 전송한 후 서버에서 s3에 등록후 해당 url을 받아 이를 렌더링하는 형식으로 변경
close #907
> feat: 이미지 삽입기능 구현(FE)

- frontend/src/apis/studylogs.ts
- frontend/src/components/Editor/StudylogEditor.tsx
- frontend/src/constants/message.js
- frontend/src/constants/reactQueryKey.js
- frontend/src/hooks/Studylog/useTempSavedStudylog.ts
- frontend/src/hooks/queries/studylog.ts
- frontend/src/models/Ability.ts
- frontend/src/models/Studylogs.ts
- frontend/src/pages/NewStudylogPage/index.tsx
- frontend/src/types/utils.ts
- 글 작성시 임시 저장 기능을 구현했습니다.
- 임시저장한 글을 불러오는 함수는 아래와 같습니다. useQuery를 사용하여 onSuccess일 때, editor에 들어가는 내용들을 업데이트해주고 있습니다. 아래의 방법에 대해서 어떻게 생각하시는 지 궁금합니다!!
```typescript
const fetchTempSavedStudylogRequest: UseQueryResult<
AxiosResponse<TempSavedStudyLog>,
AxiosError
> = useQuery(
[REACT_QUERY_KEY.TEMP_STUDYLOG, username],
() =>
requestGetTempSavedStudylog({
accessToken: localStorage.getItem(LOCAL_STORAGE_KEY.ACCESS_TOKEN) as string,
}),
{
refetchOnWindowFocus: false,
onSuccess: ({ data }) => {}
);
```
> feat: 임시 저장 기능 구현

- backend/src/main/java/wooteco/prolog/roadmap/application/dto/KeywordCreateRequest.java
- backend/src/main/java/wooteco/prolog/roadmap/application/dto/KeywordResponse.java
- backend/src/main/java/wooteco/prolog/roadmap/application/dto/KeywordUpdateRequest.java
- backend/src/main/java/wooteco/prolog/roadmap/application/dto/KeywordsResponse.java
- backend/src/main/java/wooteco/prolog/roadmap/application/dto/QuizRequest.java
- backend/src/main/java/wooteco/prolog/roadmap/application/dto/QuizResponse.java
- backend/src/main/java/wooteco/prolog/roadmap/application/dto/QuizzesResponse.java
- backend/src/main/java/wooteco/prolog/roadmap/ui/KeywordController.java
- backend/src/main/java/wooteco/prolog/roadmap/ui/QuizController.java
- 컨트롤러에서 단순히 Response DTO를 반환하는 방식으로 구현했습니다.
- Keyword 단건 조회, 세션별 Keyword 목록 조회 기능에도 Response에 childrenKeywords 필드가 추가됐습니다. (필드만 존재, 값은 항상 null)
- 실제 기능 merge 전 충돌 해결이 필요합니다.
close #1110
> feat: 로드맵 Mock API 구현

- frontend/src/GlobalStyles.js
- frontend/src/components/TopKeywordList/TopKeywordList.tsx
#1240 PR을 다시 작성하였습니다.
로드맵 상위 키워드 버튼입니다.
|변경 전|변경 후|
|-|-|
|![image](https://user-images.githubusercontent.com/20203944/233588800-c8039540-6320-4953-a190-3b257873b2fb.png)|![image](https://user-images.githubusercontent.com/20203944/233588893-9d63c0df-3302-40b5-814b-e6627bcba2a3.png)|
스크롤 바 디자인입니다.
크롬, Safari, Edge 에서 잘 적용된 것을 확인하였습니다. 
파이어폭스의 경우 일부 CSS 적용이 불가하여 일부만 구현되었습니다. 적용이 불가한 CSS 속성은 아래와 같습니다.
```css
overflow-y: overlay;
border-radius: 4px;
```
close #1236
> Feature/#1236 로드맵 상위 키워드 버튼과 스크롤 바 디자인 개선

- frontend/src/components/Items/PopularStudylogItem.tsx
- frontend/src/pages/MainPage/RecentStudylogList.tsx
- frontend/src/pages/RoadmapPage/index.tsx
[바로가기](https://github.com/woowacourse/prolog/issues/1239)
- 변경 전
- 변경 후
- 변경 전
- 변경 후
- 변경 전
- 변경 후
- 페어와 상의한 결과 위치를 가운데로 바꾸면 다른 변경사항들(학습목록 글)에 영향이 가는 문제로 변경을 보류하였습니다!
- close  #1239
> Refactor/#1239 학습로그 및 로드맵에 margin css 개선

- .github/workflows/front-dev.yml
- .github/workflows/front-prod.yml
Close #1271
<br><br>
* GitHub Actions dev, prod 배포 스크립트 수정
* node 버전 16 사용하도록 설정
* 의존성 설치 시 yarn.lock에 있는 버전 그대로 설치하도록 수정
* cache가 기능하도록 수정
Workflow 성공 확인: https://github.com/woowacourse/prolog/actions/runs/4934344749
> build: node 버전 명시 및 의존성 최신버전 사용 방지

- frontend/src/components/NavBar/NavBar.js
- frontend/src/constants/screenSize.js
>#1270
> 화면의 사이즈를 줄였을 때, 헤더의 버튼 텍스트가 여러줄로 보이는 현상을 수정
> 모바일 버전일 경우 아이콘 로고로 변경
> <img width="500" alt="스크린샷 2023-05-12 오후 4 32 34" src="https://github.com/woowacourse/prolog/assets/72205402/8cd8db6a-6097-4c34-98a5-5147e75522f5">
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요.
> text 깨짐 현상이 dev 서버에서는 안 보였습니다. 그래서 첫번째 작업 내용은 prolog 홈페이지에서 개발자 도구에서 변경 후 스크린샷을 찍어서 올립니당.
> Refactor/1270 헤어 콘텐츠 깨짐 현상 수정 및 모바일 버전 로고 변경

- backend/src/acceptanceTest/java/wooteco/prolog/AcceptanceHooks.java
- #1358 
- 인수 테스트 이후 @After 어노테이션으로 데이터 초기화
> Fix/#1358 인수테스트(큐컴버)와 통합테스트 간의 독립성을 보장한다.

- backend/src/acceptanceTest/java/wooteco/prolog/AcceptanceHooks.java
- #1358 
- 인수 테스트 이후 @After 어노테이션으로 데이터 초기화
> Fix/#1358 인수테스트(큐컴버)와 통합테스트 독립

- backend/src/acceptanceTest/java/wooteco/prolog/AcceptanceContext.java
- backend/src/acceptanceTest/java/wooteco/prolog/steps/EssayAnswerStepDefinitions.java
- backend/src/acceptanceTest/resources/wooteco/prolog/essayanswer.feature
- backend/src/main/java/wooteco/prolog/roadmap/application/dto/EssayAnswerUpdateRequest.java
- backend/src/main/java/wooteco/prolog/roadmap/ui/EssayAnswerController.java
>
> #1357 
- 로드맵 관련 큐컴버 테스트 추가
- 로드맵 답변 수정 기능 추가
> Feature/#1357 로드맵 답변 수정 기능

- frontend/src/apis/essayanswers.ts
- frontend/src/hooks/EssayAnswer/useEssayAnswer.ts
- frontend/src/hooks/queries/essayanswer.ts
- frontend/src/models/EssayAnswers.ts
- frontend/src/pages/EditEssayAnswerPage/index.tsx
- frontend/src/pages/EssayAnswerPage/index.tsx
- frontend/src/pages/index.js
- frontend/src/routes.js
close #1356
로드맵에서 내가 작성한 글의 경우 `수정` 버튼이 나오도록 추가했어요.
수정 버튼을 눌렀을 때 로드맵 글 수정 페이지로 이동하는 기능을 추가했어요.
페이지 로딩 후 서버와 통신해서 글의 기존 내용을 가져와요!
> Feature/#1356 로드맵 답변 수정 기능

- frontend/src/hooks/queries/essayanswer.ts
close #1376
기존: 로드맵 퀴즈에 등록한 답변을 수정 시 같은 답변 id를 가진 학습로그 글로 이동하는 버그
수정: 수정한 답변 글 상세보기로 이동
> Fix/#1376 로드맵 답변 수정 후 페이지 이동 문제 해결

- .github/workflows/front-prod.yml
fix: 프로덕션 배포 yml의 타입채킹 무시 옵션 임시 활성화
> fix: 프로덕션 배포 yml의 타입채킹 무시 옵션 임시 활성화

- backend/src/main/java/wooteco/prolog/roadmap/application/RoadMapService.java
- backend/src/main/java/wooteco/prolog/roadmap/application/dto/KeywordsResponse.java
- backend/src/main/java/wooteco/prolog/roadmap/domain/Keyword.java
- backend/src/main/java/wooteco/prolog/roadmap/domain/repository/KeywordRepository.java
- backend/src/main/java/wooteco/prolog/roadmap/ui/RoadmapController.java
- backend/src/test/java/wooteco/prolog/roadmap/application/RoadMapServiceTest.java
- backend/src/test/java/wooteco/prolog/roadmap/repository/KeywordRepositoryTest.java
- #1461 
커리큘럼 ID로 키워드들 조회
- 세션 ID 사용 X
> feat : 커리큘럼 ID로 키워드들 조회 API 구현

- backend/src/main/java/wooteco/prolog/article/application/OgTagParser.java
Hotfix: og 태그가 없는 경우 null 을 반환하여 생기는 NPE 해결을 위해 빈문자열 반환
> Hotfix: og 태그가 없는 경우 null 을 반환하여 생기는 NPE 해결을 위해 빈문자열 반환

- backend/src/main/java/wooteco/prolog/studylog/domain/StudylogDocument.java
- backend/src/main/java/wooteco/prolog/studylog/domain/StudylogDocumentQueryBuilder.java
> ES 쿼리 로직 수정

- backend/src/acceptanceTest/java/wooteco/prolog/steps/QuizStepDefinitions.java
- backend/src/documentation/java/wooteco/prolog/docu/QuizDocumentation.java
- backend/src/main/java/wooteco/prolog/roadmap/application/QuizService.java
- backend/src/main/java/wooteco/prolog/roadmap/application/dto/EssayAnswerQuizResponse.java
- backend/src/main/java/wooteco/prolog/roadmap/application/dto/EssayAnswerResponse.java
- backend/src/main/java/wooteco/prolog/roadmap/application/dto/QuizzesResponse.java
- backend/src/main/java/wooteco/prolog/roadmap/domain/repository/EssayAnswerRepository.java
- backend/src/main/java/wooteco/prolog/roadmap/ui/EssayAnswerController.java
- backend/src/main/java/wooteco/prolog/roadmap/ui/QuizController.java
- backend/src/test/java/wooteco/prolog/roadmap/application/EssayAnswerSearchTest.java
- backend/src/test/java/wooteco/prolog/roadmap/application/QuizServiceTest.java
#1474
퀴즈 응답 DTO에 학습 여부 정보를 Boolean 값으로 추가했습니다.
학습 여부는 퀴즈에 대해 답변 게시글을 작성한 경우 true가 됩니다.
> Feature/1474 키워드의 퀴즈 목록을 조회할 때 각 퀴즈 별로 학습 여부를 알 수 있다

- backend/src/documentation/java/wooteco/prolog/docu/KeywordDocumentation.java
- backend/src/main/java/wooteco/prolog/roadmap/application/RoadMapService.java
- backend/src/main/java/wooteco/prolog/roadmap/application/dto/KeywordResponse.java
- backend/src/main/java/wooteco/prolog/roadmap/domain/repository/EssayAnswerRepository.java
- backend/src/main/java/wooteco/prolog/roadmap/ui/RoadmapController.java
- backend/src/test/java/wooteco/prolog/roadmap/application/RoadMapServiceTest.java
- backend/src/test/java/wooteco/prolog/roadmap/repository/EssayAnswerRepositoryTest.java
- #1473 
- RoadmapService의 전체 키워드 조회 시 현재 로그인 유저의 진도율을 표시한다
- 기존의 KeywordController, KeywordService는 어드민에서 쓰는 것 같은데 얘네는 반영하지 않았습니다.
- RoadmapController와 RoadmapService만 진행했습니다.
> 전체 키워드 조회 시 학습 진도를 포함한다

- backend/src/documentation/java/wooteco/prolog/docu/KeywordDocumentation.java
- backend/src/main/java/wooteco/prolog/roadmap/application/dto/KeywordResponse.java
- closed #1542
- 생성자의 오버로딩 버전(문제 원인) 제거
> KeywordResponse에서 추천 포스트 emptyList 반환 로직 제거

- backend/src/main/java/wooteco/prolog/roadmap/application/KeywordService.java
- backend/src/main/java/wooteco/prolog/roadmap/domain/repository/KeywordRepository.java
- backend/src/main/java/wooteco/prolog/roadmap/ui/KeywordController.java
- backend/src/main/java/wooteco/prolog/roadmap/ui/QuizController.java
- backend/src/test/java/wooteco/prolog/roadmap/repository/KeywordRepositoryTest.java
- #1525 
- 기존 기능은 놔두고 newXXX 가 session ID가 없는 메서드
- 추후 기존 기능을 삭제하고, newXXX 메서드를 사용할 예정
> refactor : 엔드포인트에서 사용하지 않는 session ID가 있으면, 없애고 새로운 엔드포인트 생성

- frontend/src/apis/articles.ts
- frontend/src/apis/index.ts
- frontend/src/components/Article/Article.style.tsx
- frontend/src/components/Article/Article.tsx
- frontend/src/components/Reaction/Like.tsx
- frontend/src/hooks/queries/article.ts
- frontend/src/mocks/db/articles-android.json
- frontend/src/mocks/db/articles-backend.json
- frontend/src/mocks/db/articles-frontend.json
- frontend/src/mocks/db/articles.json
- frontend/src/mocks/handlers/articles.ts
- frontend/src/models/Article.ts
#1552 
아티클에 좋아요 기능을 추가하고 authorization null 삭제하였습니다.
> Feat/#1552: 아티클 좋아요 기능 추가와 authorization null 삭제

- frontend/src/apis/articles.ts
- frontend/src/components/Article/Article.tsx
- frontend/src/contexts/UserProvider.js
- frontend/src/hooks/queries/article.ts
- frontend/src/mocks/handlers/articles.ts
- frontend/src/pages/ArticleListPage/index.tsx
#1566
비크루 권한을 추가하였습니다.
현재, userProvider가 js로 되어있습니다.
따라서 임시로 role을 빈값으로 주어 크루 권한을 처리하였습니다.
> Feature/#1566 비크루 권한 처리 및 조회수 API 추가

- frontend/src/pages/RoadmapPage/components/Roadmap/SubKeyword.tsx
resolve #1603
* Safari에서 로드맵 퀴즈 progress가 표시되지 않는 오류를 수정하였습니다
> Safari에서 로드맵 퀴즈 progress가 표시되지 않는 오류를 수정

- backend/src/main/java/wooteco/prolog/studylog/domain/StudylogDocument.java
- backend/src/main/java/wooteco/prolog/studylog/domain/StudylogDocumentQueryBuilder.java
> #1522
>
> Date 타입 수정 및 Date 쿼리 필터 삭제
> refactor: ES dateTime 타입 및 쿼리 필터 수정

- backend/src/documentation/adoc/quiz.adoc
- backend/src/documentation/java/wooteco/prolog/docu/QuizDocumentation.java
- backend/src/main/java/wooteco/prolog/roadmap/application/QuizService.java
- backend/src/main/java/wooteco/prolog/roadmap/application/dto/CurriculumQuizResponse.java
- backend/src/main/java/wooteco/prolog/roadmap/domain/repository/QuizRepository.java
- backend/src/main/java/wooteco/prolog/roadmap/ui/QuizController.java
- backend/src/test/java/wooteco/prolog/roadmap/repository/QuizRepositoryTest.java
- #1607 
커리큘럼 별 퀴즈 검색 기능을 구현했습니다. 
중첩 Join 문을 사용했는데, 흐름이 curriculum -> session -> keyword -> quiz 순으로 진행하려 했고
그 이유는 드라이빙 테이블의 컬럼을 줄이기 위해서입니다.
Join 과정에서 session 이 curriculum에 대한 인덱스가 없어 풀테이블 스캔을 하는데 session 의 경우 사용하지 않을 데이터면서 데이터가 그렇게 많이 생길 것 같지도 않기에 인덱스는 생략했습니다
> 커리큘럼 별 퀴즈 API 생성

- backend/src/main/java/wooteco/prolog/roadmap/application/KeywordService.java
- backend/src/main/java/wooteco/prolog/roadmap/application/RoadMapService.java
- backend/src/main/java/wooteco/prolog/roadmap/application/dto/KeywordResponse.java
- backend/src/main/java/wooteco/prolog/roadmap/application/dto/KeywordsResponse.java
- backend/src/main/java/wooteco/prolog/roadmap/domain/Keyword.java
- backend/src/main/java/wooteco/prolog/roadmap/domain/repository/KeywordRepository.java
- backend/src/main/java/wooteco/prolog/roadmap/domain/repository/QuizRepository.java
- backend/src/main/java/wooteco/prolog/roadmap/domain/repository/dto/KeywordIdAndAnsweredQuizCount.java
- backend/src/main/java/wooteco/prolog/roadmap/domain/repository/dto/KeywordIdAndDoneQuizCount.java
- backend/src/main/java/wooteco/prolog/roadmap/domain/repository/dto/KeywordIdAndTotalQuizCount.java
- backend/src/test/java/wooteco/prolog/roadmap/application/RecommendedPostServiceTest.java
- backend/src/test/java/wooteco/prolog/roadmap/application/RoadMapServiceTest.java
- backend/src/test/java/wooteco/prolog/roadmap/repository/KeywordRepositoryTest.java
- #1609 
- `roadmap` 패키지의 모든 Repository를 사용해서 자바 API를 통해 조립하던 기존 로직을 JPQL을 통해 개선했습니다.
- 커리큘럼 ID에 해당하는 모든 키워드를 조회하는 `findAllByCurriculumId()` 구현
- 키워드 ID 별로 총 퀴즈 개수를 조회하는 `findTotalQuizCount()` 구현
- 키워드 ID 별로 현재 멤버가 답변한 총 퀴즈 개수를 조회하는 `findDoneQuizCountByMemberId()` 구현
- 세션 ID에 해당하는 키워드들을 한 번에 조회할 수 있다
- 커리큘럼 ID에 해당하는 모든 세션의 모든 키워드들을 한 번에 조회할 수 있다
- 각 키워드별 총 퀴즈 개수도 같이 반환한다
- 로그인한 유저가 조회하면 각 키워드별 답변한 총 퀴즈 개수도 같이 반환한다
- 비로그인한 유저가 조회하면 각 키워드별 답변한 총 퀴즈 개수는 0개이다
> 로드맵 서비스 로직 가독성 개선

- backend/src/main/java/wooteco/prolog/roadmap/application/KeywordService.java
- backend/src/main/java/wooteco/prolog/roadmap/application/RoadMapService.java
- backend/src/main/java/wooteco/prolog/roadmap/application/dto/KeywordResponse.java
- backend/src/main/java/wooteco/prolog/roadmap/application/dto/KeywordsResponse.java
- backend/src/main/java/wooteco/prolog/roadmap/domain/Keyword.java
- backend/src/main/java/wooteco/prolog/roadmap/domain/repository/KeywordRepository.java
- backend/src/main/java/wooteco/prolog/roadmap/domain/repository/QuizRepository.java
- backend/src/main/java/wooteco/prolog/roadmap/domain/repository/dto/KeywordIdAndAnsweredQuizCount.java
- backend/src/main/java/wooteco/prolog/roadmap/domain/repository/dto/KeywordIdAndDoneQuizCount.java
- backend/src/main/java/wooteco/prolog/roadmap/domain/repository/dto/KeywordIdAndTotalQuizCount.java
- backend/src/test/java/wooteco/prolog/roadmap/application/RecommendedPostServiceTest.java
- backend/src/test/java/wooteco/prolog/roadmap/application/RoadMapServiceTest.java
- backend/src/test/java/wooteco/prolog/roadmap/repository/KeywordRepositoryTest.java
- #1609 
- `roadmap` 패키지의 모든 Repository를 사용해서 자바 API를 통해 조립하던 기존 로직을 JPQL을 통해 개선했습니다.
- 커리큘럼 ID에 해당하는 모든 키워드를 조회하는 `findAllByCurriculumId()` 구현
- 키워드 ID 별로 총 퀴즈 개수를 조회하는 `findTotalQuizCount()` 구현
- 키워드 ID 별로 현재 멤버가 답변한 총 퀴즈 개수를 조회하는 `findDoneQuizCountByMemberId()` 구현
- 세션 ID에 해당하는 키워드들을 한 번에 조회할 수 있다
- 커리큘럼 ID에 해당하는 모든 세션의 모든 키워드들을 한 번에 조회할 수 있다
- 각 키워드별 총 퀴즈 개수도 같이 반환한다
- 로그인한 유저가 조회하면 각 키워드별 답변한 총 퀴즈 개수도 같이 반환한다
- 비로그인한 유저가 조회하면 각 키워드별 답변한 총 퀴즈 개수는 0개이다
> 로드맵 서비스 로직 리팩토링

- backend/src/main/java/wooteco/prolog/roadmap/application/dto/KeywordResponse.java
- backend/src/test/java/wooteco/prolog/roadmap/application/RoadMapServiceTest.java
- #1621 
- answeredQuizCount -> doneQuizCount로 변경
> 응답 DTO의 필드명 변경으로 인한 버그 수정

- backend/src/acceptanceTest/java/wooteco/prolog/steps/KeywordRecommendedPostStepDefinitions.java
- backend/src/main/java/wooteco/prolog/login/ui/LoginConfig.java
- backend/src/main/java/wooteco/prolog/login/ui/LoginInterceptor.java
- backend/src/main/java/wooteco/support/autoceptor/AuthenticationDetector.java
- backend/src/main/java/wooteco/support/autoceptor/AutoInterceptorPatternMaker.java
- backend/src/main/java/wooteco/support/autoceptor/LoginDetector.java
- backend/src/main/java/wooteco/support/autoceptor/MethodPattern.java
- backend/src/main/java/wooteco/support/autoceptor/scanner/MappingAnnotation.java
- backend/src/main/java/wooteco/support/autoceptor/scanner/URIScanner.java
- backend/src/test/java/wooteco/support/autoceptor/MethodPatternTest.java
- backend/src/test/java/wooteco/support/autoceptor/URIScannerTest.java
#1612 
```java
@GetMapping("/sessions/{sessionId}/keywords/{keywordId}/quizs/{quizId}")
public ResponseEntity<QuizResponse> findQuizById(@PathVariable Long quizId,
@AuthMemberPrincipal LoginMember member) {
return ResponseEntity.ok(quizService.findById(quizId, member.getId()));
}
@DeleteMapping("/sessions/{sessionId}/keywords/{keywordId}/quizs/{quizId}")
public ResponseEntity<Void> deleteQuiz(@PathVariable Long sessionId,
@PathVariable Long keywordId,
@PathVariable Long quizId) {
quizService.deleteQuiz(quizId);
return ResponseEntity.noContent().build();
}
```
위와 같은 상황에서 Delete method에서도 로그인 검증이 일어나는 문제가 있었습니다.
이를 MethodPattern 이란 객체를 생성하여 메서드와 uri 두 가지가 만족해야 검증하도록 변경했습니다.
> LoginInterceptor 개선

- backend/src/acceptanceTest/java/wooteco/prolog/steps/KeywordRecommendedPostStepDefinitions.java
- backend/src/main/java/wooteco/prolog/login/ui/LoginConfig.java
- backend/src/main/java/wooteco/prolog/login/ui/LoginInterceptor.java
- backend/src/main/java/wooteco/support/autoceptor/AuthenticationDetector.java
- backend/src/main/java/wooteco/support/autoceptor/AutoInterceptorPatternMaker.java
- backend/src/main/java/wooteco/support/autoceptor/LoginDetector.java
- backend/src/main/java/wooteco/support/autoceptor/MethodPattern.java
- backend/src/main/java/wooteco/support/autoceptor/scanner/MappingAnnotation.java
- backend/src/main/java/wooteco/support/autoceptor/scanner/URIScanner.java
- backend/src/test/java/wooteco/support/autoceptor/MethodPatternTest.java
- backend/src/test/java/wooteco/support/autoceptor/URIScannerTest.java
#1612 
```java
@GetMapping("/sessions/{sessionId}/keywords/{keywordId}/quizs/{quizId}")
public ResponseEntity<QuizResponse> findQuizById(@PathVariable Long quizId,
@AuthMemberPrincipal LoginMember member) {
return ResponseEntity.ok(quizService.findById(quizId, member.getId()));
}
@DeleteMapping("/sessions/{sessionId}/keywords/{keywordId}/quizs/{quizId}")
public ResponseEntity<Void> deleteQuiz(@PathVariable Long sessionId,
@PathVariable Long keywordId,
@PathVariable Long quizId) {
quizService.deleteQuiz(quizId);
return ResponseEntity.noContent().build();
}
```
위와 같은 상황에서 Delete method에서도 로그인 검증이 일어나는 문제가 있었습니다.
이를 MethodPattern 이란 객체를 생성하여 메서드와 uri 두 가지가 만족해야 검증하도록 변경했습니다.
> 로그인 Interceptor 개선

- backend/src/main/resources/db/migration/prod/V10__fix_table_group_and_member.sql
> fix: department flyway script

- backend/src/main/java/wooteco/prolog/interview/infrastructure/FakeInterviewer.java
- backend/src/main/java/wooteco/prolog/interview/ui/InterviewController.java
- backend/src/main/resources/db/migration/prod/V15__create_table_interview.sql
- frontend/src/components/NavBar/NavBar.tsx
- frontend/src/constants/path.ts
- frontend/src/pages/InterviewPage/InterviewPage.tsx
- frontend/src/pages/InterviewPage/InterviewSession.tsx
- frontend/src/pages/InterviewPage/InterviewSetup.tsx
- frontend/src/pages/InterviewPage/index.tsx
- frontend/src/pages/index.ts
- frontend/src/routes.js
#1641 연관된 프론트엔드 작업
레벨 인터뷰 프론트 기능 구현
>
> feat: 레벨 인터뷰 페이지 연동

- .github/workflows/sonar-build.yml
- frontend/src/pages/InterviewPage/InterviewSession.tsx
- frontend/src/pages/InterviewPage/InterviewSetup.tsx
이 풀 리퀘스트는 `InterviewPage` 컴포넌트에서 API 호출 방식을 리팩터링하여 각 파일마다 새로운 Axios 인스턴스를 생성하는 대신 중앙 집중화된 `client` 모듈을 사용하도록 변경했습니다. 또한, `InterviewSetup`에서 조건문 로직과 에러 처리에 대한 소폭 개선도 포함되어 있습니다.
* `InterviewSession` 및 `InterviewSetup` 컴포넌트(`frontend/src/pages/InterviewPage/InterviewSession.tsx`, `frontend/src/pages/InterviewPage/InterviewSetup.tsx`)에서 로컬로 정의된 Axios 인스턴스(`api`)를 공유 `client` 모듈로 교체했습니다. [[1]] [[2]]
* `InterviewSession`에서 `/answers`, `/restart`, `/quit` 등의 엔드포인트에 대한 모든 API 호출을 `client.post`로 변경했습니다. [[1]] [[2]] [[3]]
* `InterviewSetup`에서 `/sessions/mine`, `/missions`, `/questions`, `/interviews` 등의 엔드포인트에 대해 `client.get` 및 `client.post`를 사용하도록 API 호출을 업데이트했습니다. [[1]] [[2]] [[3]] [[4]]
* `InterviewSetup` 내 `selectedSession` 및 `selectedMission`에 대한 조건문을 단순화하여 중복 코드를 줄였습니다. [[1]] [[2]]
* …
> fix: 인터뷰 페이지에서 공통된 API 콜 하도록 수정

- backend/src/main/java/wooteco/prolog/session/application/MissionService.java
- backend/src/main/java/wooteco/prolog/session/domain/repository/MissionRepository.java
- backend/src/main/java/wooteco/prolog/session/ui/MissionController.java
다음은 `sessionId`를 기준으로 미션을 필터링하는 기능을 백엔드에 추가한 풀 리퀘스트입니다. 이 변경은 `MissionController`, `MissionService`, `MissionRepository`에 반영되었습니다. 주요 변경 사항은 다음과 같습니다:
* **MissionController**: `showMissions` 엔드포인트에 선택적 `sessionId` 쿼리 파라미터를 추가했습니다. `sessionId`가 제공되면 해당 세션 ID에 해당하는 미션들만 반환하고, 없으면 전체 미션을 반환합니다.  
(`backend/src/main/java/wooteco/prolog/session/ui/MissionController.java`)
* **MissionService**: 특정 세션 ID에 해당하는 미션 목록을 조회하는 `findAllBySessionId` 메서드를 추가했습니다.  
(`backend/src/main/java/wooteco/prolog/session/application/MissionService.java`)
* **MissionRepository**: 세션 ID로 미션을 조회하는 `findBySessionId` 메서드를 추가했습니다.  
(`backend/src/main/java/wooteco/prolog/session/domain/repository/MissionRepository.java`)
* `MissionController`에서 `@RequestParam`을 포함한 import 구문을 정리하고, 전체 import 구조를 개선했습니다. …
> feat(interview): 세션을 기준으로 미션을 필터링
