woowacourse/prolog

frontend/src/components/Card/Card.js
frontend/src/components/Card/Card.stories.js

feat: Card 컴포넌트 및 스토리북 작성

---

frontend/src/components/Card/Card.js
frontend/src/components/SelectBox/SelectBox.js
frontend/src/components/SelectBox/SelectBox.stories.js
frontend/src/components/index.js

feat: SelectBox 컴포넌트 및 스토리북 작성

---

frontend/src/App.js
frontend/src/components/Button/Button.js
frontend/src/components/Card/Card.js
frontend/src/components/SelectBox/SelectBox.js
frontend/src/components/index.js
frontend/src/constants/path.js
frontend/src/pages/NewPostPage/index.js

- Router 문법 오류 수정
- path 수정(post/new => post/write)
- 컴포넌트 SIZE 변수 명 수정 및 export(SIZE => CARD_SIZE, SIZE => BUTTON_SIZE)
- NewPost page 마크업 구현

feat: NewPost page 마크업 구현 및 refactoring

---

backend/src/main/java/wooteco/studylog/login/GithubLoginController.java
backend/src/main/java/wooteco/studylog/login/TokenRequest.java
backend/src/main/java/wooteco/studylog/login/TokenResponse.java

github에서 받아온 `code`를 보내면 `아주좋은토큰`을 반환하는 `/login/token` api를 작성했습니다.
`{ code: "아무스트링코드" }` 요청으로 확인할 수 있습니다!

feat(게스트 로그인) : 더미 토큰을 생성하는 api 작성

---

backend/src/main/java/wooteco/studylog/post/web/controller/PostController.java
backend/src/main/java/wooteco/studylog/post/web/controller/dto/AuthorResponse.java
backend/src/main/java/wooteco/studylog/post/web/controller/dto/CategoryResponse.java
backend/src/main/java/wooteco/studylog/post/web/controller/dto/PostRequest.java
backend/src/main/java/wooteco/studylog/post/web/controller/dto/PostResponse.java

feat(학습로그 작성, 전체보기) : dummy API 추가

---

frontend/package.json
frontend/src/components/Card/NewPostCard.js
frontend/src/components/SelectBox/SelectBox.js
frontend/src/components/index.js
frontend/src/pages/NewPostPage/index.js
frontend/yarn.lock

- newPostPage 기능 구현
- window OS 에서 Post에 한글을 입력할 때, focus가 원하는 영역으로 이동하지 않는 문제를 해결

feat: NewPostPage 글 작성 기능 구현

---

backend/src/main/resources/schema.sql

이슈 : #51 
1. post테이블 content칼럼의 타입 수정
2. drop table문 순서 조정
3. INNO_DB 설정 제거

fix(backend) : h2 및 mysql 모두에서 범용적인 DB 스키마 파일로 수정

---

backend/src/main/java/wooteco/prolog/WebConfig.java
backend/src/main/resources/application.yml
frontend/.env.production.local
frontend/.gitignore
frontend/package.json
frontend/src/components/GithubLogin/GithubLogin.js
frontend/src/hooks/useGetFetch.js
frontend/src/redux/actions/postAction.js
frontend/src/redux/actions/userAction.js

chore: env for deploy

---

backend/src/main/resources/schema.sql

fix/schema-edit 브랜치말고 새로운 브랜치로 다시 pr 합니다.
member 테이블 스키마도 #51 에서 말했던 방식으로 수정했습니다!

fix(backend) : 스키마 문법 통일

---

frontend/package.json
frontend/yarn.lock

- win-nodw-env 삭제
- cross-env 추가

chore: window에 맞춘 환경 설정 변경

---

backend/src/main/java/wooteco/prolog/filter/application/dto/FilterResponse.java
backend/src/main/java/wooteco/prolog/filter/ui/FilterController.java
backend/src/main/java/wooteco/prolog/login/application/AuthorizationExtractor.java
backend/src/main/java/wooteco/prolog/login/application/GithubLoginService.java
backend/src/main/java/wooteco/prolog/login/application/JwtTokenProvider.java
backend/src/main/java/wooteco/prolog/login/application/MemberService.java
backend/src/main/java/wooteco/prolog/login/application/dto/GithubProfileResponse.java
backend/src/main/java/wooteco/prolog/login/application/dto/MemberResponse.java
backend/src/main/java/wooteco/prolog/login/application/dto/TokenRequest.java
backend/src/main/java/wooteco/prolog/login/application/dto/TokenResponse.java
backend/src/main/java/wooteco/prolog/login/dao/MemberDao.java
backend/src/main/java/wooteco/prolog/login/domain/AuthMemberPrincipal.java
backend/src/main/java/wooteco/prolog/login/excetpion/MemberNotFoundException.java
backend/src/main/java/wooteco/prolog/login/excetpion/TokenNotValidException.java
backend/src/main/java/wooteco/prolog/login/ui/AuthMemberPrincipalArgumentResolver.java
backend/src/main/java/wooteco/prolog/login/ui/LoginConfig.java
backend/src/main/java/wooteco/prolog/login/ui/LoginInterceptor.java
backend/src/main/java/wooteco/prolog/login/ui/MemberController.java
backend/src/main/java/wooteco/prolog/mission/application/dto/MissionResponse.java
backend/src/main/java/wooteco/prolog/post/application/dto/AuthorResponse.java
backend/src/main/java/wooteco/prolog/post/application/dto/PostRequest.java
backend/src/main/java/wooteco/prolog/post/application/dto/PostResponse.java
backend/src/main/resources/static/index.html
backend/src/test/java/wooteco/prolog/AcceptanceTest.java
backend/src/test/java/wooteco/prolog/Documentation.java
backend/src/test/java/wooteco/prolog/filter/FilterDocumentation.java
backend/src/test/java/wooteco/prolog/login/LoginAcceptanceTest.java
backend/src/test/java/wooteco/prolog/login/LoginDocumentation.java
backend/src/test/java/wooteco/prolog/tag/TagAcceptanceTest.java

feat : members/me api 구현 및 토큰 검증 로직 구현

---

backend/src/main/java/wooteco/prolog/DataLoaderApplicationListener.java
backend/src/test/java/wooteco/prolog/AcceptanceTest.java
backend/src/test/java/wooteco/prolog/post/acceptance/PostAcceptanceTest.java

fix: token response for acceptance test

---

backend/src/main/java/wooteco/prolog/login/ui/MemberController.java
backend/src/test/java/wooteco/prolog/AcceptanceTest.java
backend/src/test/java/wooteco/prolog/Documentation.java
backend/src/test/java/wooteco/prolog/login/AuthMemberPrincipalTestArgumentResolver.java
backend/src/test/java/wooteco/prolog/login/GithubTestController.java
backend/src/test/java/wooteco/prolog/login/LoginAcceptanceTest.java
backend/src/test/java/wooteco/prolog/post/acceptance/PostAcceptanceTest.java

fix: documentation

---

backend/src/docs/asciidoc/post.adoc
backend/src/main/java/wooteco/prolog/post/application/PostService.java
backend/src/main/java/wooteco/prolog/post/dao/PostDao.java
backend/src/main/java/wooteco/prolog/post/exception/AuthorNotValidException.java
backend/src/main/java/wooteco/prolog/post/ui/PostController.java
backend/src/main/java/wooteco/prolog/tag/application/TagService.java
backend/src/main/java/wooteco/prolog/tag/dao/PostTagDao.java
backend/src/test/java/wooteco/prolog/Documentation.java
backend/src/test/java/wooteco/prolog/post/PostDocumentation.java
backend/src/test/java/wooteco/prolog/post/acceptance/PostAcceptanceTest.java

feat: 포스트 수정 기능 구현

---

frontend/src/components/NavBar/NavBar.js
frontend/src/constants/api.js

로그아웃 버튼 클릭 및 accessToken 만료 시 로그아웃 기능 구현

feat: 로그아웃 기능 구현

---

backend/src/main/java/wooteco/prolog/tag/application/TagService.java
backend/src/main/java/wooteco/prolog/tag/dao/PostTagDao.java
backend/src/main/java/wooteco/prolog/tag/dao/TagDao.java
backend/src/test/java/wooteco/prolog/tag/TagAcceptanceFixture.java
backend/src/test/java/wooteco/prolog/tag/TagDocumentation.java
backend/src/test/java/wooteco/prolog/tag/TagStepDefinitions.java
backend/src/test/resources/wooteco/prolog/acceptance/tag.feature

feat : 연동된 포스트가 없는 태그는 노출되지 않도록 수정

---

backend/src/test/java/wooteco/prolog/filter/FilterDocumentation.java
backend/src/test/java/wooteco/prolog/login/LoginDocumentation.java
backend/src/test/java/wooteco/prolog/mission/MissionDocumentation.java
backend/src/test/java/wooteco/prolog/post/documentation/PostDocumentation.java
backend/src/test/java/wooteco/prolog/tag/TagDocumentation.java

- 테스트 이름 통일
- 테스트 형식 통일 (PostDocumentation 작업중)

feat: documentation 리팩토링

---

backend/src/test/java/wooteco/prolog/documentation/AuthMemberPrincipalTestArgumentResolver.java
backend/src/test/java/wooteco/prolog/tag/TagDocumentation.java

#161 
- 작성자별 조회 시 500 응답하는 문제
- 태그 목록 조회 테스트가 실패하는 문제
상기 오류 발견하고 해결하였습니다~

fix: 문서화에서 발견된 문제 해결

---

frontend/src/components/Card/NewPostCard.js

일단 정책이 정해지기 전 까진 막아두는건 어때요?ㅎㅎ
이미지 입력하려고 하면 이렇게 뜹니다ㅎㅎ

feature(create-post): prevent upload image

---

backend/src/main/java/wooteco/prolog/post/dao/PostDao.java

fix : 태그가 없는 자료가 안 나오는 오류 수정

---

frontend/src/components/NavBar/NavBar.js
frontend/src/pages/MainPage/index.js
frontend/src/redux/actions/userAction.js

*   사이트 최초 진입 시 alert 삭제 및 글쓰기 버튼을 누를때 accessToken이 없을 시 alert추가
*   members/me 관련 로직 크게 봐야 할 것 같아서 이슈 등록 후 추후에 수정하겠습니다 .

fix: 사이트 최초 진입 시 alert 삭제 및 글쓰기 버튼을 누를때 accessToken이 없을 시 alert추가

---

frontend/src/components/NavBar/NavBar.js
frontend/src/pages/MainPage/index.js

fix #186 
*   localStorage가 잘못되어 있어 accessToken 을 찾지 못하는 버그가 있었음.
*   access\_token => accessToken 으로 키 이름 수정함.

fix: localStorage key가 잘못 작성되어있던 오류 해결

---

frontend/env/.env.development
frontend/env/.env.local
frontend/env/.env.production
frontend/src/components/NavBar/NavBar.js
frontend/src/components/NavBar/NavBar.styles.js

feat: local, dev, prod 환경에 따른 로고 표시 변경

---

backend/src/main/java/wooteco/prolog/aop/exception/BadRequestCode.java
backend/src/main/java/wooteco/prolog/post/application/PostService.java
backend/src/main/java/wooteco/prolog/post/exception/PostNotFoundException.java

fix(post): no post message

---

backend/src/main/java/wooteco/prolog/post/dao/PostDao.java

fix(post): post ResultSetExtractor

---

frontend/src/components/NavBar/NavBar.js

resolve #178 
로고 클릭시 홈으로 이동 + 새로고침 추가했습니다.

feat: 로고 클릭시 새로고침 추가

---

backend/src/main/java/wooteco/prolog/aop/exception/BadRequestCode.java
backend/src/main/java/wooteco/prolog/login/excetpion/PostTitleTooLongException.java
backend/src/main/java/wooteco/prolog/post/application/PostService.java
frontend/src/components/Card/NewPostCard.js
frontend/src/components/Card/NewPostCard.styles.js
frontend/src/constants/index.js
frontend/src/constants/input.js
frontend/src/constants/message.js
frontend/src/redux/actions/postAction.js

fixes #210 
우선 메시지 노출하는 부분 수정했습니다.
추후 작성완료 버튼을 누르기 전에 에러 상황을 노출하면 좋을 것 같아요 :)

fix: 글자수 제한 안내 메시지 노출

---

backend/src/main/java/wooteco/prolog/post/dao/PostDao.java
frontend/src/pages/MainPage/index.js
frontend/src/pages/ProfilePagePosts/index.js
frontend/src/service/requests.js

fix: profilePagePost 페이지네이션 적용

---

.ebextensions/01-set-timezone.config

UTC 타임 존 asia seoul로 수정

---

backend/PrologJavaStyle.xml

- `prolog/backend/PrologJavaStyle.xml` 파일 추가되었습니다.
- [백엔드 코드 컨벤션](https://github.com/woowacourse/prolog/wiki/%EB%B0%B1%EC%97%94%EB%93%9C-%EC%BD%94%EB%93%9C-%EC%BB%A8%EB%B2%A4%EC%85%98) 위키 작성해두었습니다!

백엔드 자바코드 스타일 xml 파일 추가

---

frontend/src/components/FilterList/FilterList.js

선택된 레벨의 미션만 노출하기

---

backend/src/main/resources/application.yml
frontend/src/hooks/useFilterWithParams.js
frontend/src/pages/MainPage/index.js
frontend/src/pages/PostPage/index.js
frontend/src/pages/PostPage/styles.js
frontend/src/pages/ProfilePagePosts/index.js

fix: PostPage에서 markdown 넘어가는 버그 수정

---

frontend/src/hooks/usePost.js
frontend/src/pages/EditPostPage/index.js
frontend/src/pages/PostPage/index.js
frontend/src/pages/PostPage/styles.js

closes #211 
UI가 자신 없네요. 단순하게 구현해봤는데, 개선할 점을 알려주시면 고치도록 하겠습니다!
기존의 usePost에서 에러처리 부분에 오류가 있는 것 같아서 같이 수정했습니다.(return 값만 추가한 것이라서 기존에 사용하던 부분에 오류가 발생하진 않을거에요!)

feat: 내 글에서 수정/삭제 기능 추가

---

backend/src/main/resources/logback-access.xml
backend/src/main/resources/logback-spring.xml
backend/src/main/resources/logback/console-logger.xml
backend/src/main/resources/logback/debug-logger.xml
backend/src/main/resources/logback/file-access-logger.xml
backend/src/main/resources/logback/file-debug-logger.xml
backend/src/main/resources/logback/file-error-logger.xml
backend/src/main/resources/logback/file-info-logger.xml
backend/src/main/resources/logback/file-warn-logger.xml

오타 몇 가지를 발견해서 픽스해보았습니당!
appender 파일명과 이름 규칙(순서)가 통일되면 좋을거 같아 조금 바꿔보았습니당!
file, console 명명이 확실히 구분되지 않아 헷갈린거 같아서 file로 붙였는데 괜찮은지 모르겠네용..

fix: 백엔드 로깅

---

frontend/src/components/Chip/Chip.js
frontend/src/components/Chip/Chip.styles.js
frontend/src/components/NavBar/NavBar.js
frontend/src/pages/MainPage/index.js
frontend/src/pages/MainPage/styles.js
frontend/src/pages/ProfilePagePosts/index.js
frontend/src/pages/ProfilePagePosts/styles.js

refactor: 선택된 필터 목록에 필터 타입 추가

---

frontend/src/pages/MainPage/index.js
frontend/src/pages/ProfilePage/index.js
frontend/src/pages/ProfilePage/styles.js
frontend/src/pages/ProfilePagePosts/index.js
frontend/src/service/requests.js

fix #378 #376 
- ProfilePage에서 글 목록 안 나타나는 현상 수정
- ProfilrPage에 태그 부분에 스크롤 추가

fix: ProfilePage에서 글 목록 안 나타나는 현상 수정

---

frontend/src/GlobalStyles.js
frontend/src/components/NavBar/NavBar.js
frontend/src/components/ProfilePageSideBar/ProfilePageSideBar.js
frontend/src/components/ProfilePageSideBar/ProfilePageSideBar.styles.js
frontend/src/pages/MainPage/index.js
frontend/src/service/requests.js

close #222 
<div>
</div>
UI 관련해서 다른 의견 주시면 반영하겠습니다!
그리고 닉네임 길이 제한을 받는 것이 좋을 것 같습니다. 우선은 20글자로 제한했습니다. 추후 글자 수가 정해진다면 변경하겠습니다.
작업 내용
- 로그 버튼을 클릭했을 때, 리로드되던 문제를 해결했습니다. 
- 회원 닉네임을 수정 기능을 추가했습니다. 
- input의 font를 global font와 동일하도록 `font-family: inherit`을 추가했습니다.
리뷰 부탁드려요~

회원 닉네임 수정 기능 추가

---

.github/workflows/sonar-build.yml
backend/build.gradle
settings.gradle

resolve #396 
sonarCloud를 적용합니다.
관련 내용은 wiki에 정리하겠습니다.

[CI] PR 검증을 위한 SonarCloude를 적용한다.

---

frontend/package.json
frontend/src/App.js
frontend/src/components/@shared/Icons/CancelIcon.js
frontend/src/components/Button/Button.js
frontend/src/components/Button/PageButton.js
frontend/src/components/NavBar/NavBar.js
frontend/src/components/NavBar/NavBar.styles.js
frontend/src/components/ProfileChip/ProfileChip.js
frontend/src/components/SelectBox/SelectBox.js
frontend/src/pages/NewPostPage/index.js
frontend/src/pages/PostPage/index.js
frontend/src/pages/ProfilePage/styles.js

closes #427 
개발자 도구에 보이는 경고를 모두 해결했습니다. 메인페이지 뿐만 아니라 다른 페이지도 모두 해결했습니다.
주의사항으로는 의존성 관련 eslint가 제대로 동작하지 않는 부분이 많아서 의존성 관련 eslint를 off했습니다.

개발자 도구에 보이는 경고 해결

---

backend/build.gradle
backend/src/main/resources/logback-spring.xml
backend/src/main/resources/logback/slack-logger.xml

related #433 
dev, prod 500에러시 슬랙 알림이 난다

500에러시 슬랙 알람 기능 추가

---

frontend/src/GlobalStyles.js
frontend/src/components/ProfilePageSideBar/ProfilePageSideBar.js
frontend/src/components/ProfilePageSideBar/ProfilePageSideBar.styles.js
frontend/src/service/requests.js

충돌하면서 누락된 닉네임 수정 기능 코드가 있어서 삽입했습니다.
수정하면서 `members/me API`를 `members/{username}` 으로 수정하였습니다!

fix: 삭제된 닉네임 수정 기능 코드 삽입

---

backend/src/main/java/wooteco/prolog/studylog/application/StudylogService.java
backend/src/main/java/wooteco/prolog/studylog/ui/StudylogController.java
backend/src/test/java/wooteco/prolog/studylog/studylog/application/StudylogServiceTest.java

멤버가 스크랩을 하여도 개별 조회의 경우 scrap여부가 false로 오던 오류 수정

fix: 스크랩 후 개별 조회시 true가 반환되도록 수정

---

frontend/src/components/Chip/Chip.styles.js
frontend/src/components/NavBar/NavBar.js
frontend/src/utils/textColorPicker.js

fix #473 
*   getColorText 사용 시 예상하지 못한 값이 파라미터로 넘어오는 데서 발생하는 에러 처리
*   로고 클릭시 root로 이동 & reload 로직 삭제

fix: 함수 적용 시 잘못 적용된 부분 해결 및 reload 로직 삭제

---

.gitignore
frontend/package.json
frontend/src/react-app-env.d.ts
frontend/tsconfig.json
frontend/yarn.lock

fix: #495
프론트엔드 타입스크립트 추가
*   전체 마이그레이션이 아닌, 이후 개발되는 코드 우선 ts 적용 예정

chore: 프론트엔드 타입스크립트 의존성 추가

---

backend/src/main/java/wooteco/prolog/report/domain/report/common/UpdateUtil.java

버그 가능성이 있는 로직 수정합니다.
close #531

[리포트] 업데이트 관련 로직을 변경한다. #531

---

search/mapping-index-and-sync/HELP.md

sh 스크립트 HELP.md 파일에 sh 명령어가 빠져있어 추가했습니당
바로 머지하겠습니다!
related #521

[검색] index-mapping 쉘 스크립트 명령어를 추가한다.

---

search/docker-compose-dev.yml
search/docker-compose-prod.yml
search/mapping-index-and-sync/mapping-index-and-sync.sh

kib 버전을 7.14.1로 수정하고 sh 스크립트 equals 문법을 수정했습니다.
이것도 코드에는 영향이 없어 우선 바로 머지하겠습니다!!

feat: kib 버전 수정 및 sh 문법 오류 수정

---

backend/src/main/java/wooteco/prolog/report/domain/report/Report.java

[리포트] 리포트 이름 길이를 30자로 늘린다.

---

frontend/src/hooks/useUserStudyLogs.js
frontend/src/pages/ProfilePageNewReport/StudyLogModal.js

resolve #489
리포트 수정, 생성 시 학습로그 추가  모달 레벨 필터에 전체보기 추가
티케가 잘 만들어주신 덕분에 추가 바로 할 수 있었네용 👍

feat: 리포트 수정, 생성 시 학습로그 추가  모달 레벨 필터에 전체보기 추가

---

frontend/src/pages/ProfilePagePosts/index.js
frontend/src/utils/object.ts

fix: 프로필 페이지 학습로그 필터에서 멤버 필터 삭제

---

backend/build.gradle
backend/src/main/resources/application.yml

어플리케이션 모니터링을 위해 actuator 의존성 설정과 prometheus 설정을 했습니다!
dev 는 직접 돌려보면서 확인이 되었고 해당 코드가 main 브랜치에 들어가면 prod api 도 설정이 완료됩니다!

feat: actuator 및 prometheus 설정 추가

---

frontend/src/components/Lists/StudyLogList.tsx
frontend/src/hooks/usePost.js
frontend/src/hooks/useStudyLog.js
frontend/src/pages/PostPage/index.js
frontend/src/types/type.d.ts

- 리액션 관련 프론트엔드 충돌 해결
- usePost 가 없는 이슈 해결
- 파라미터 순서가 변경되어있는 이슈 해결
- 미로그인시 에러핸들링 추가

fix: 리액션 관련 프론트엔드 충돌 해결

---

frontend/src/pages/PostPage/index.js
frontend/src/styles/flex.styles.js

fix #639 
- 조회수가 2씩 증가하는 이슈 수정
- page component 이름은 추후 변경 예정

fix: 조회수가 2씩 증가하는 이슈 수정

---

frontend/src/pages/LoginCallbackPage/index.js

fix: 로그인 처리 시 로딩상태가 반영되지 않고 바로 라우팅 시키는 이슈 해결

---

frontend/src/pages/StudylogPage/index.js

fix #693
*   비 로그인 시 post 요청이 한번만 가게끔 수정
*   로그인 시 Members/me 요청이 우선순위가 높도록 임시 코드 적용 -> 추후 비동기 제어 관련 로직 추가 필요하나 학습 필요함.

fix: 조회수가 2씩 증가하는 오류 수정

---

backend/src/acceptanceTest/java/wooteco/prolog/steps/MemberStepDefinitions.java
backend/src/main/java/wooteco/prolog/member/ui/MemberReactionController.java
frontend/src/service/requests.js

스크랩 API 수정

---

frontend/env/.env.development
frontend/env/.env.production
frontend/package.json
frontend/src/App.js
frontend/src/hooks/useStudylog.js
frontend/src/pages/NewStudylogPage/index.js
frontend/src/pages/StudylogPage/index.js
frontend/yarn.lock

구글 애널리틱스 모니터링을 위한 구글 태그 매니저 등록

---

frontend/src/pages/AbilityPage/StudyLogs/SelectAbilityBox.js
frontend/src/pages/AbilityPage/StudyLogs/StudyLogTable.js
frontend/src/pages/AbilityPage/index.js
frontend/src/pages/ProfilePageEditReport/index.js

- 리포트 수정시 날짜가 default 값이 안들어가는 오류
- 역량 맵핑시 삭제가 안되는 오류
- 역량 맵핑시 refetch가 안되는 오류
p.s. 서니덕분.. 감사합니다ㅠㅠ

fix: 리포트, 역량페이지 버그 수정

---

backend/src/documentation/java/wooteco/prolog/docu/FilterDocumentation.java
backend/src/main/java/wooteco/prolog/DataLoaderApplicationListener.java
backend/src/main/java/wooteco/prolog/login/domain/AuthMemberPrincipal.java
backend/src/main/java/wooteco/prolog/session/application/MissionService.java
backend/src/main/java/wooteco/prolog/session/application/SessionMemberService.java
backend/src/main/java/wooteco/prolog/session/application/SessionService.java
backend/src/main/java/wooteco/prolog/session/application/dto/MissionResponse.java
backend/src/main/java/wooteco/prolog/session/domain/repository/MissionRepository.java
backend/src/main/java/wooteco/prolog/session/domain/repository/SessionMemberRepository.java
backend/src/main/java/wooteco/prolog/session/ui/MissionController.java
backend/src/main/java/wooteco/prolog/session/ui/SessionController.java
backend/src/main/java/wooteco/prolog/studylog/application/FilterService.java
backend/src/main/java/wooteco/prolog/studylog/application/dto/StudylogResponse.java
backend/src/main/java/wooteco/prolog/studylog/ui/FilterController.java
frontend/src/apis/studylogs.ts
frontend/src/components/Editor/Sidebar.tsx
frontend/src/components/FilterList/FilterList.styles.js
frontend/src/components/FilterList/SelectedFilterList.js
frontend/src/components/Items/PopularStudylogItem.tsx
frontend/src/hooks/queries/filters.ts
frontend/src/models/Studylogs.ts

- 학습로그 작성 페이지 > 세션과 미션은 자신이 수강중인 강의만 선택이 가능
- 학습로그 목록 페이지 > 필터에서 세션과 미션은 자신이 수강중인 강의가 먼저 노출하는 기능

수강중인 세션과 미션에 대한 처리

---

frontend/src/components/Items/PopularStudylogItem.styles.ts
frontend/src/components/Items/PopularStudylogItem.tsx
frontend/src/pages/MainPage/styles.ts

#838 
- 프로필, 제목, 태그와 내용에 준다.(제외: 날짜,)
- 나머지는 pointer 주지 않는다.
- 애니메이션 추가

feat: Card hover 시 가시성 향상을 위해 UI 개선

---

frontend/src/components/DropdownMenu/DropdownMenu.styles.js
frontend/src/components/NavBar/NavBar.js
frontend/src/components/NavBar/NavBar.styles.js

feat: GNB 드롭다운 메뉴 추가

---

backend/src/acceptanceTest/java/wooteco/prolog/fixtures/SessionAcceptanceFixture.java
backend/src/acceptanceTest/java/wooteco/prolog/fixtures/StudylogAcceptanceFixture.java
backend/src/acceptanceTest/java/wooteco/prolog/steps/StudylogStepDefinitions.java
backend/src/documentation/java/wooteco/prolog/docu/MemberDocumentation.java
backend/src/documentation/java/wooteco/prolog/docu/StudylogDocumentation.java
backend/src/main/java/wooteco/prolog/DataLoaderApplicationListener.java
backend/src/main/java/wooteco/prolog/session/domain/Session.java
backend/src/main/java/wooteco/prolog/studylog/application/DocumentService.java
backend/src/main/java/wooteco/prolog/studylog/application/PopularStudylogService.java
backend/src/main/java/wooteco/prolog/studylog/application/StudylogService.java
backend/src/main/java/wooteco/prolog/studylog/application/dto/PopularStudylogsResponse.java
backend/src/main/java/wooteco/prolog/studylog/application/dto/StudylogWithScrapedCountResponse.java
backend/src/main/java/wooteco/prolog/studylog/application/dto/StudylogsWithScrapCountResponse.java
backend/src/main/java/wooteco/prolog/studylog/domain/Curriculum.java
backend/src/main/java/wooteco/prolog/studylog/domain/Studylog.java
backend/src/main/java/wooteco/prolog/studylog/domain/repository/StudylogScrapRepository.java
backend/src/main/java/wooteco/prolog/studylog/ui/PopularStudylogController.java
backend/src/main/java/wooteco/prolog/studylog/ui/StudylogController.java
backend/src/main/resources/static/index.html
backend/src/test/java/wooteco/prolog/studylog/studylog/application/PopularStudylogServiceTest.java

- 인기있는 학습로그를 통합으로 제공
- 학습로그에서 스크랩 수 제공 x
- 인기있는 학습로그 스크랩 수 제공 x
https://github.com/woowacourse/prolog/issues/881
https://github.com/woowacourse/prolog/issues/883
PR이 늦어진 점 죄송합니다 😭 [이전 리뷰](https://github.com/woowacourse/prolog/pull/897)에서 반영되지 않았던 부분은 리팩토링 하겠습니다

feat: 인기있는 학습로그 카테고리 별 제공 기능 및 스크랩 수를 제공하는 기능구현

---

frontend/src/components/Reaction/Scrap.styles.ts
frontend/src/components/Reaction/Scrap.tsx
frontend/src/pages/StudylogPage/Content.js
frontend/src/pages/StudylogPage/index.js

hotfix: 학습로그 렌더링 되지 않는 현상 해결

---

frontend/src/components/Items/PopularStudylogItem.styles.ts
frontend/src/components/Items/PopularStudylogItem.tsx
frontend/src/mocks/browser.js
frontend/src/mocks/db/popularStudyLog.json
frontend/src/mocks/fixture.js
frontend/src/mocks/handlers.js
frontend/src/models/Studylogs.ts
frontend/src/pages/MainPage/PopularStudyLogList.tsx
frontend/src/pages/MainPage/styles.ts

**저번에 올린 PR에서 서버 스키마 변경 및 스크랩 수만 제거한 PR입니다.**
이전 스프린트에서 StudyLog 서버 스키마 구조가 변경되었습니다. 
배포 후 장애가 있어서, 이전 버전으로 롤백하고 스키마 변경에 대응 하였습니다.
서버 단에서 StudyLog를 참조하고 있는 곳이 많아 scrapCount 프로퍼티 하나를 추가하기 어려워서
이번에 스크랩수를 제외하고, UI 변경만 고려하였습니다.
서버에서 먼저 develop으로 머지한 후, rebase 받아서 정상적으로 서비스가 동작하는지 확인하고 머지하겠습니다.

refactor: 인기있는 학습로그에서 스크랩 수 제거

---

batch/src/main/java/kr/co/techcourse/prolog/batch/application/MemberService.java
batch/src/main/java/kr/co/techcourse/prolog/batch/domain/Member.java
batch/src/main/java/kr/co/techcourse/prolog/batch/domain/MemberRepository.java
batch/src/main/java/kr/co/techcourse/prolog/batch/job/sample/tasklet/EdenBatchJob.java

안녕하세요 손너잘! 에덴입니다.
손너잘의 PR을 보면서 기존에 있던 코드로 영차영차 열심히 짜보았습니다.
짜고보니 되게 객체스럽지 않고 함수만 남은 것 같네요 😢
테스트도 너잘의 PR과 비교해가면서 짜보려고 했는데 아직은 모르는게 많아서 테스트코드 작성이 쉽지가 않아 이번 과제에서는 배치 잡 관련 로직만 구현하게 되었습니다.
많은 지적 부탁드립니다 🙇‍♂️

feat: sample batch job 과제 구현

---

batch/build.gradle
batch/src/main/java/kr/co/techcourse/prolog/batch/job/sample/tasklet/SampleBatchJob.java
batch/src/main/java/kr/co/techcourse/prolog/batch/member/Member.java
batch/src/main/java/kr/co/techcourse/prolog/batch/member/MemberRepository.java

feat: sample batch job 과제 구현 

---

backend/src/documentation/java/wooteco/prolog/docu/CommentDocumentation.java
backend/src/main/resources/static/index.html

학습로그 작성 시 역량 매핑 기능 Merge시, 발생한 충돌 에러 해결

---

batch/src/main/java/kr/co/techcourse/prolog/batch/job/sample/chunk/eve/NumberChunkBatchJob.java
batch/src/main/java/kr/co/techcourse/prolog/batch/job/sample/chunk/eve/entity/Number.java
batch/src/main/java/kr/co/techcourse/prolog/batch/job/sample/tasklet/east/domain/Member.java
batch/src/main/java/kr/co/techcourse/prolog/batch/job/sample/tasklet/east/repository/MemberRepository.java
batch/src/main/java/kr/co/techcourse/prolog/batch/job/sample/tasklet/east/service/MemberService.java
batch/src/main/java/kr/co/techcourse/prolog/batch/job/sample/tasklet/eden/application/MemberService.java
batch/src/main/java/kr/co/techcourse/prolog/batch/job/sample/tasklet/eden/domain/Member.java
batch/src/main/java/kr/co/techcourse/prolog/batch/job/sample/tasklet/eden/domain/MemberRepository.java
batch/src/main/java/kr/co/techcourse/prolog/batch/job/sample/tasklet/eve/domain/Member.java
batch/src/main/java/kr/co/techcourse/prolog/batch/job/sample/tasklet/eve/domain/MemberRepository.java
batch/src/main/java/kr/co/techcourse/prolog/batch/job/sample/tasklet/verus/member/Member.java
batch/src/main/java/kr/co/techcourse/prolog/batch/job/sample/tasklet/verus/member/MemberRepository.java

안녕하세요! 이브입니다.
이번에도 샘플 코드와 JpaPagingReader, JpaItmeWriter, ListItemReader 키워드 주신 거 참고해서 열심히 구현해 봤습니다👀
리뷰 부탁드려요!🙂

feat: chunk batch job 과제 구현

---

batch/src/main/java/kr/co/techcourse/prolog/batch/BatchApplication.java
batch/src/main/java/kr/co/techcourse/prolog/batch/job/sample/chunk/east/EastChunkBatchJob.java
batch/src/main/java/kr/co/techcourse/prolog/batch/job/sample/chunk/east/entity/Numbers.java
batch/src/main/java/kr/co/techcourse/prolog/batch/job/sample/chunk/east/entity/NumbersRepository.java

안녕하세요 손너잘!
이번 과제는 힌트 주신 키워드를 이용해서 구현해 보았습니다 👍
개인적으로 tasklet으로 작업했을 때 보다 편리하다고 느껴졌네요!
과제로 많은 도움 되었습니다 😄

feat: sample batch chunk job 과제 구현

---

frontend/src/components/Comment/Comment.tsx
frontend/src/mocks/db/comments.json
frontend/src/mocks/handlers/comment.ts
frontend/src/models/Comment.ts

- 댓글 스키마에서 member -> author 로 프로퍼티 명 변경했습니다.

refactor: 댓글 스키마 변경에 따른 프로퍼티 명 변경

---

backend/src/main/resources/db/migration/prod/V26__create_comment_table.sql

#953 PR 작업했던 부분의 comment 테이블에 대해서 flyway 추가

chore: flyway에 comment DDL 추가

---

backend/src/main/java/wooteco/prolog/common/ResourceSizeAdvice.java

body값이 collection인 경우 헤더를 추가하여 응답하는 로직 추가
```
HTTP/1.1 200 
Vary: Origin
...
X-Total-Count: 3
...
```

react admin을 위한 응답 헤더 추가

---

frontend/src/components/Editor/Sidebar.tsx
frontend/src/components/Editor/StudylogEditor.tsx
frontend/src/pages/EditStudylogPage/index.tsx

close #967 
Co-authored-by: JUDONGHYEOK <JUDONGHYEOK@users.noreply.github.com>

feat: 학습로그 수정 시 매핑된 역량 수정 기능 UI

---

backend/src/main/java/wooteco/prolog/common/AuditingEntity.java
backend/src/main/java/wooteco/prolog/studylog/application/dto/CommentResponse.java

댓글 생성날짜 조회 시, `2022-09-04T14:24:49` 로 출력
댓글 생성날짜 조회 시, @JsonFormat을 이용해 `2022-09-04 14:24:49` 로 출력

feat: 댓글 조회의 날짜 형식 변경

---

frontend/src/contexts/UserProvider.js

새로고침 시 로그인 풀리는 문제 해결
getlocalStorageItem 메서드에서 JSON.parse 에러가 발생해서 이 부분 고쳤습니다.
close #1012

fix: 새로고침 시 로그인 풀리는 문제 해결

---

frontend/src/components/NavBar/NavBar.js
frontend/src/routes.js

레벨로그 배포를 다음으로 미룹니다.
v1.5.0 버전에서 레벨로그 기능을 일시적으로 제거합니다.
release 1.5.0 으로 PR 날립니다.

chore: 레벨로그 기능 일시적으로 제거

---

frontend/src/pages/ProfilePageStudylogs/index.js

#828 이슈에 대해 버그가 있어 revert 합니다!

Revert "fix: 내 학습로그에서 뒤로가기를 3번해야 작동하는 문제 해결 (#1034)"

---

frontend/.storybook/main.js
frontend/src/components/Button/ResponsiveButton.stories.js
frontend/src/components/Button/ResponsiveButton.tsx
frontend/src/components/KeywordSection/KeywordSection.stories.js
frontend/src/components/KeywordSection/KeywordSection.tsx
frontend/src/components/LabelledImage/LabelledImage.stories.js
frontend/src/components/LabelledImage/LabelledImage.tsx

작업 브랜치를 develop, main 에 머지합니다.

feat: 로드맵을 위한 하위 컴포넌트 구현

---

docs/frontend/README.md

docs: 프론트엔드 문서 작성

---

docs/backend/ERD.md

docs: DB ERD 문서화 추가

---

docs/backend/인가과정.md

docs: 인가과정 문서화 추가

---

backend/src/main/java/wooteco/prolog/common/WebConfig.java
backend/src/main/resources/db/migration/prod/V31__create_keyword_table.sql
backend/src/main/resources/db/migration/prod/V32__create_quiz_table.sql
backend/src/main/resources/db/migration/prod/V33__create_studylogtempability_table.sql

flyway 로 정상 작동하는지 확인을 하지 않아서 발생한 문제
dev 와 병합하면서 flyway 31 번 파일이 중첩됨.
(두개가 생김) 
flyway 에서 어떤걸 31번째로 실행해야할지 몰라서 서버 자체가 안뜨는 문제가 생김.
int 타입으로 정의해둔 필드를 BIGINT 로 flyway 에 명시해두어서 발생한 문제
```java
org.springframework.beans.factory.BeanCreationException:
Error creating bean with name 'entityManagerFactory' 
defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]:
Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: 
default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: wrong column type encountered in column [importance] in table [keyword]; found [bigint (Types#BIGINT)], but expecting [integer …
```

feat: flyway migration 31~ 33 fix 

---

backend/src/main/java/wooteco/prolog/common/WebConfig.java

fix: flyway migration setting 제거

---

frontend/src/apis/keywords.ts
frontend/src/apis/session.ts
frontend/src/components/CurriculumList/CurriculumList.tsx
frontend/src/components/Editor/Sidebar.tsx
frontend/src/components/KeywordList/KeywordList.styles.ts
frontend/src/components/KeywordList/KeywordList.tsx
frontend/src/components/SessionList/SessionList.tsx
frontend/src/components/TopKeywordList/TopKeywordList.tsx
frontend/src/hooks/queries/curriculum.ts
frontend/src/hooks/queries/keywords.ts
frontend/src/mocks/fixtures/curriculums.ts
frontend/src/mocks/fixtures/keywords.ts
frontend/src/mocks/fixtures/sessions.ts
frontend/src/models/Keywords.ts
frontend/src/models/Studylogs.ts
frontend/src/pages/EditStudylogPage/index.tsx
frontend/src/pages/NewStudylogPage/index.tsx
frontend/src/pages/RoadmapPage/index.tsx

커밋 메시지 참고
- fix - 커리큘럼 로드맵 UI 로직과 서버 응답값 불일치로 인한 에러 해결
- 에러 이유 : API 명세서와 다른 응답값
- 해결 방법 : 서버에서 받는 응답값대로 프론트엔드 로직 수정
- feat -  마지막으로 본 로드맵(커리큘럼)을 로컬스토리지에 기억하고 호출 기능 추가
```bash
cd backend
./gradlew bootRun --args='--spring.profiles.active=local'
```
```bash
cd frontend
yarn run start:local
```
```bash
cd frontend
yarn run start:dev
```
```javascript
// index.js의 다음 msw 로직을 잠시 주석 처리
if (process.env.NODE_ENV === 'development') {
const { worker } = require('./mocks/browser');
worker.start();
}
```
```bash
cd frontend
yarn run start:dev
```
- 배포된 백엔드 개발 서버를 바라보는 프론트엔드 개발 환경을 실행한 테스트 결과
https://user-images.githubusercontent.com/59413128/212399713-529ba6f5-c592-4f31-8648-e27a4481b70e.mov

fix: 커리큘럼 로드맵 UI 로직과 서버 응답값 불일치로 인한 에러 해결

---

backend/src/acceptanceTest/java/wooteco/prolog/steps/GroupMemberStepDefinitions.java
backend/src/documentation/java/wooteco/prolog/docu/StudylogDocumentation.java
backend/src/main/java/wooteco/prolog/member/domain/MemberGroup.java
backend/src/main/java/wooteco/prolog/studylog/application/PopularStudylogService.java
backend/src/main/java/wooteco/prolog/studylog/application/dto/PopularStudylogsResponse.java
backend/src/test/java/wooteco/prolog/studylog/studylog/application/PopularStudylogServiceTest.java
frontend/src/mocks/db/popularStudyLog.json
frontend/src/models/Studylogs.ts

fix #1198 
리팩터링은 #1199 이슈로 별도로 진행하겠습니다.

fix(popular studylog): 인기있는 학습로그 조회 시 발생하는 에러 수정

---

.github/workflows/back-dev.yml
.github/workflows/back-prod.yml
.github/workflows/front-dev.yml
.github/workflows/front-prod.yml

version up build environment
see https://github.com/actions/runner-images/issues/6002

github action 빌드 환경 수정

---

backend/src/test/java/wooteco/prolog/badge/domain/FourthCrewSessionsTest.java
backend/src/test/java/wooteco/prolog/roadmap/application/EssayAnswerServiceTest.java
backend/src/test/java/wooteco/prolog/roadmap/application/KeywordServiceTest.java
backend/src/test/java/wooteco/prolog/roadmap/application/QuizServiceTest.java
backend/src/test/java/wooteco/prolog/roadmap/domain/EssayAnswerTest.java

EssayAnswerService
KeywordService
QuizService
FourthCrewSessions
EssayAnswer
테스트 코드 작성

Test/#1232 푸우, 연어 테스트 작성

---

backend/src/test/java/wooteco/prolog/studylog/application/StudylogServiceTest.java
backend/src/test/java/wooteco/prolog/studylog/domain/StudylogTest.java

- StudylogService (insertStudylog, insertStudylogTemp 2개 메서드와 여기에서 사용하는 private 메서드)
- Studylog

Feature/1232 ocean raon 테스트 코드 작성

---

backend/src/test/java/wooteco/prolog/studylog/application/StudylogServiceTest.java
backend/src/test/java/wooteco/prolog/studylog/domain/StudylogTest.java

- StudylogService (insertStudylog, insertStudylogTemp 2개 메서드와 여기에서 사용하는 private 메서드)
- Studylog

Feature/1232 ocean raon 테스트 코드 작성 

---

frontend/src/GlobalStyles.js
frontend/src/components/Banner/Banner.styles.ts
frontend/src/components/Banner/BannerList.styles.ts
frontend/src/components/Banner/BannerList.tsx
frontend/src/components/NavBar/NavBar.js

Refactor/#1242 메인화면 배너 깨짐과 글쓰기 시 헤더의 cursor pointer가 안 되는 문제 해결

---

backend/src/test/java/wooteco/prolog/member/domain/MemberGroupTest.java
backend/src/test/java/wooteco/prolog/studylog/application/PopularStudylogServiceTest.java

- MemberGroup
- name에 포함되어 있는 그룹명을 체크하여 그룹명만 반환하는 기능 테스트 작성
- PopularStudylogService
- 인기 학습로그를 갱신해주는 기능 테스트 작성
- 인기 학습로그를 찾아 응답에 담아 반환해주는 기능 테스트 작성

Feature/#1232 져니, 스플릿 테스트 작성

---

frontend/src/GlobalStyles.js
frontend/src/components/Banner/Banner.styles.ts
frontend/src/components/Banner/BannerList.styles.ts
frontend/src/components/Banner/BannerList.tsx
frontend/src/components/NavBar/NavBar.js

#1242 
> 
문제
해결
문제
해결
#1247 
이미 리뷰 받은 내용입니다.

Refactor/1242 메인화면 배너 깨짐과 글쓰기 시 헤더의 cursor pointer가 안 되는 문제 해결

---

frontend/src/components/Items/PopularStudylogItem.tsx
frontend/src/pages/MainPage/RecentStudylogList.tsx
frontend/src/pages/RoadmapPage/index.tsx

> #1239
dev에 merge된 커밋을 main에 반영하려고 합니다.
- 변경 전
- 변경 후
<br />
- 변경 전
- 변경 후
<br />
- 변경 전
- 변경 후
>

Refactor/1239 margin design improve main 반영

---

backend/src/test/java/wooteco/prolog/session/application/SessionMemberServiceTest.java

fix: registerMembers코드 삭제

---

backend/src/test/java/wooteco/prolog/studylog/application/IntegratedStudylogServiceTest.java
backend/src/test/java/wooteco/prolog/studylog/application/StudylogServiceTest.java

> #1280 
> StudylogService 에 대한 테스트 코드작성
>

Feature/#1280 푸우,연어,주디,우르 테스트 작성

---

backend/src/test/java/wooteco/prolog/studylog/application/IntegratedStudylogServiceTest.java
backend/src/test/java/wooteco/prolog/studylog/application/StudylogServiceTest.java

Feature/#1280 푸우,연어,주디,우르 테스트 작성

---

backend/src/test/java/wooteco/prolog/studylog/application/StudylogSessionServiceTest.java
backend/src/test/java/wooteco/prolog/studylog/application/StudylogTagServiceTest.java
backend/src/test/java/wooteco/prolog/studylog/application/TagServiceTest.java
backend/src/test/java/wooteco/prolog/studylog/application/ViewedStudyLogCookieGeneratorTest.java

#1280
아래 클래스들의 메서드에 대한 테스트 코드를 작성하였다.
- StudylogSessionService
- StudylogTagService
- TagService
- ViewedStudyLogCookieGenerator
없습니다!

Feature/#1280 홍실, 아마란스 테스트 작성

---

backend/src/test/java/wooteco/prolog/studylog/application/CommentServiceTest.java
backend/src/test/java/wooteco/prolog/studylog/application/StudylogScrapServiceTest.java

>
#1280
---
- CommentService, StudylogScrapService 테스트 코드 고도화를 진행하였습니다.
---
>
- 테스트 코드에서 부족한 부분이 있다면 얼마든지 말씀해 주세요!

Feature/#1280 져니, 스플릿 테스트 작성

---

backend/src/test/java/wooteco/prolog/member/application/GroupMemberServiceTest.java
backend/src/test/java/wooteco/prolog/member/application/MemberTagServiceTest.java

#1309 
- GroupMemberServiceTest
- MemberTagServiceTest

Feature/1309 홍실 아마란스 테스트 작성

---

frontend/src/components/@shared/SideSheet/SideSheet.style.ts
frontend/src/pages/RoadmapPage/styles.tsx

> #1315
> 로드맵의 양쪽에 마진을 준다.
- 변경 후
> 모바일 버전의 경우 모달을 bottom sheet으로 변경한다.
- 변경 후
- close #1315

Refactor/#1315 로드맵의 스타일을 수정한다.

---

backend/src/test/java/wooteco/prolog/member/application/GroupMemberServiceTest.java
backend/src/test/java/wooteco/prolog/member/application/MemberTagServiceTest.java

#1309 
- GroupMemberServiceTest
- MemberTagServiceTest

Feature/#1309 홍실, 아마란스 테스트 작성

---

frontend/src/components/FilterList/FilterList.js
frontend/src/components/FilterList/FilterList.styles.js
frontend/src/components/ProfileChip/ProfilChip.styles.ts
frontend/src/pages/StudylogListPage/index.tsx

> #1269 
>  - [x] 화면의 사이즈를 줄였을 때: "필터 초기화" 버튼 텍스트가 여러 줄이 되는 오류
>  - [ ] 화면의 사이즈를 줄였을 때: 글쓰기 버튼의 "글쓰기" 글자가 두 줄로 되는 오류
>  - [x] (추가)화면의 사이즈를 줄였을 때: "학습로그" 제목이 깨지는 오류
문제 사진
해결 사진
1. flex-shrink와 gird를 이용해서 깨짐 현상을 조절했습니다.
2. 미디어 쿼리의 max-width를 조절해서 조금 더 화면이 클 때부터 column 형식으로 보여주도록 하였습니다.
두 번째 작업 내용은 로그인이 필요한 문제인데 로그인 관련해서 아직 처리를 못 해서 하지 못했습니다😥

refactor/#1269 반응형 디자인 깨짐 현상 수정

---

backend/src/test/java/wooteco/prolog/studylog/application/FakeStudylogDocumentServiceTest.java

> #1280 
AbstractStudylogDocumentService, StudylogDocumentService, FakeStudylogDocumentService 코드에 관한 테스트 코드 작성

Feature/#1280 오션,라온 테스트 작성 

---

backend/src/test/java/wooteco/prolog/roadmap/application/CurriculumServiceTest.java

#1309
> #1309 
CurriculumService 테스트 작성

Feature/#1309 푸우,연어 테스트 작성

---

frontend/src/components/Badge/BadgeList.styles.ts
frontend/src/components/Badge/BadgeList.tsx
frontend/src/components/ProfilePageSideBar/ProfilePageSideBar.styles.js
frontend/src/pages/ProfilePage/index.js
frontend/src/pages/ProfilePage/styles.js

> #1273
> 내 프로필 상의 css를 개선하였습니다.

Refactor/#1273 프로필 페이지 반응형 css 구현

---

frontend/package.json
frontend/src/apis/comment.ts
frontend/src/apis/curriculum.ts
frontend/src/apis/essayanswers.ts
frontend/src/apis/keywords.ts
frontend/src/apis/levellogs.ts
frontend/src/apis/studylogs.ts
frontend/src/components/Calendar/Calendar.js
frontend/src/components/ProfilePageSideBar/ProfilePageSideBar.js
frontend/src/hooks/queries/auth.ts
frontend/src/hooks/queries/profile.ts
frontend/src/hooks/queries/report.ts
frontend/src/hooks/queries/studylog.ts
frontend/src/hooks/useFetch.js
frontend/src/hooks/useImage.ts
frontend/src/hooks/useMutation.js
frontend/src/hooks/useRequest.js
frontend/src/service/requests.js
frontend/src/service/requests.ts
frontend/src/utils/axiosInstance.ts
frontend/src/utils/response.js

#1337 
fetch를 사용하는 부분을 axios로 통일하였습니다.
그 과정에서 json으로 변환하던 부분과 상태 이상일 때 에러 메세지를 던지는 부분도 axios에 맞게 수정하였습니다.
package.json의 scripts에
```js
"start:devLocal": "cp ./env/.env.development.local ./.env && cross-env NODE_ENV=development.local react-scripts start"
```
이 코드를 넣고 실행시키면 서버가 제대로 오고 있는지 확인할 수 있었습니다!
혹시 몰라서 package.json은 따로 커밋하지는 않았습니다~~
이번에 axios를 저희가 처음 써봐서 제대로 사용한 것이 맞는지 궁금합니다! 
일단 실행시켰을 때는 제대로 받아와진 거 같은데 혹~~시 잘못된 부분이 있는지 확인해주시면 감사하겠습니다.
또, 에러 메세지를 던지는 부분은 axios가 response.ok를 사용하지 못해서 
```js
if (response.status >= 400) {
throw new Error(response.statusText);
}
```
이런식으로 적었는데 괜찮은건지 궁금합니다~~!
- close #1337

Refactor/#1337 fetch하는 방식을 통일한다.

---

frontend/package.json
frontend/src/apis/comment.ts
frontend/src/apis/curriculum.ts
frontend/src/apis/essayanswers.ts
frontend/src/apis/keywords.ts
frontend/src/apis/levellogs.ts
frontend/src/apis/studylogs.ts
frontend/src/components/Calendar/Calendar.js
frontend/src/components/ProfilePageSideBar/ProfilePageSideBar.js
frontend/src/hooks/queries/auth.ts
frontend/src/hooks/queries/profile.ts
frontend/src/hooks/queries/report.ts
frontend/src/hooks/queries/studylog.ts
frontend/src/hooks/useFetch.js
frontend/src/hooks/useImage.ts
frontend/src/hooks/useMutation.js
frontend/src/hooks/useRequest.js
frontend/src/service/requests.js
frontend/src/service/requests.ts
frontend/src/utils/axiosInstance.ts
frontend/src/utils/response.js

#️⃣연관된 이슈
연관된 이슈 번호를 모두 작성해주세요
https://github.com/woowacourse/prolog/issues/1337
develop 브랜치에 merge하기 전에 main 브랜치로 먼저 merge를 해서 새로 생성했습니다.
close https://github.com/woowacourse/prolog/issues/1337

Refactor/#1337 fetch하는 방식을 통일한다. 

---

frontend/src/apis/essayanswers.ts
frontend/src/hooks/EssayAnswer/useEssayAnswer.ts
frontend/src/hooks/EssayAnswer/useEssayAnswerList.ts
frontend/src/hooks/EssayAnswer/useNewEssayAnswer.ts
frontend/src/pages/EssayAnswerPage/Content.js
frontend/src/pages/EssayAnswerPage/index.tsx
frontend/src/pages/EssayAnswerPage/styles.tsx
frontend/src/pages/NewEssayAnswerPage/index.tsx

close #1369 
#1367 PR을 머지하는 과정에서 #1363 PR과의 충돌로 인해 e31e21c 커밋을 추가로 진행했어요
`main` 브랜치에서 파생된 #1367 의 axios 사용 방식과 `develop`에 적용된 #1363 의 axios 사용 방식의 차이를 제대로 인지하지 못한 채 진행하여 [front deploy for dev #185](https://github.com/woowacourse/prolog/actions/runs/5462340240/jobs/9941567348) 에서 빌드 오류가 생겼어요
그래서 해당 문제를 수정하고 로드맵 관련 코드에서 `accessToken`이 필요하지만 사용하지 않았던 axios 코드들에 대한 수정도 진행했습니다.
추가로 로드맵 관련 파일들의 import에서 Single Quote와 Bracket Spacing 을 적용하여 가독성을 높여봤어요.

Fix/#1369 프론트엔드 빌드 오류 수정

---

backend/src/main/java/wooteco/prolog/member/domain/MemberGroup.java
backend/src/main/java/wooteco/prolog/member/domain/MemberGroupType.java
backend/src/main/java/wooteco/prolog/studylog/application/PopularStudylogService.java
backend/src/test/java/wooteco/prolog/member/domain/MemberGroupTest.java
backend/src/test/java/wooteco/prolog/member/domain/MemberGroupTypeTest.java
backend/src/test/java/wooteco/prolog/studylog/application/PopularStudylogServiceTest.java

- #1199 
기존 인기 학습로그의 내용을 바꾸지 않은 코드 개선
- close #1199

Refactor/#1199 인기 학습로그 로직 개선

---

backend/src/acceptanceTest/java/wooteco/prolog/fixtures/ArticleFixture.java
backend/src/acceptanceTest/java/wooteco/prolog/steps/ArticleStepDefinitions.java
backend/src/acceptanceTest/resources/wooteco/prolog/article.feature
backend/src/main/java/wooteco/prolog/article/domain/Article.java
backend/src/main/java/wooteco/prolog/article/domain/ArticleService.java
backend/src/main/java/wooteco/prolog/article/domain/Title.java
backend/src/main/java/wooteco/prolog/article/domain/Url.java
backend/src/main/java/wooteco/prolog/article/domain/repository/ArticleRepository.java
backend/src/main/java/wooteco/prolog/article/exception/ArticleNotFoundException.java
backend/src/main/java/wooteco/prolog/article/exception/ArticleTitleNullOrEmptyException.java
backend/src/main/java/wooteco/prolog/article/exception/ArticleTitleOverLengthException.java
backend/src/main/java/wooteco/prolog/article/exception/ArticleUrlNullOrEmptyException.java
backend/src/main/java/wooteco/prolog/article/exception/ArticleUrlOverLengthException.java
backend/src/main/java/wooteco/prolog/article/exception/InvalidArticleAuthorException.java
backend/src/main/java/wooteco/prolog/article/ui/ArticleController.java
backend/src/main/java/wooteco/prolog/article/ui/ArticleRequest.java
backend/src/main/java/wooteco/prolog/article/ui/ArticleResponse.java
backend/src/main/resources/db/migration/prod/V1.2__create_initial_scheme_squashed.sql
backend/src/test/java/wooteco/prolog/article/domain/ArticleTest.java
backend/src/test/java/wooteco/prolog/article/domain/TitleTest.java
backend/src/test/java/wooteco/prolog/article/domain/UrlTest.java

> #1353, #1354, #1355
> 아티클 추가, 아티클 전체 조회, 아티클 삭제, 아티클 수정 기능 구현
> 열려있는 API 는 추가 및 조회 만 존재

Feature/#1353 아티클 기본로직구현

---

frontend/src/apis/articles.ts
frontend/src/hooks/Articles/useArticles.ts
frontend/src/mocks/db/articles.json
frontend/src/mocks/handlers/articles.ts
frontend/src/mocks/handlers/index.ts

>#1385
articles에서 get과 post하는 api 로직을 완성하였습니다.
>
- close #1385

Feature/#1385 아티클 조회, 생성 api 로직을 구현한다. 

---

frontend/src/apis/comment.ts
frontend/src/apis/curriculum.ts
frontend/src/apis/keywords.ts
frontend/src/apis/levellogs.ts
frontend/src/apis/studylogs.ts

>
'Refactor/#1403 custom axios 리팩터링'을 main merge 하려고 합니다.
>

Refactor/#1403 custom axios 리팩터링 

---

backend/src/main/java/wooteco/prolog/roadmap/application/EssayAnswerService.java
backend/src/main/java/wooteco/prolog/roadmap/ui/EssayAnswerController.java
backend/src/test/java/wooteco/prolog/roadmap/application/EssayAnswerServiceTest.java

- #1357 
- 로드맵 관련 큐컴버 테스트 추가
- 로드맵 답변 수정 기능 추가

Feature/#1357 로드맵 답변 수정 기능

---

backend/src/main/java/wooteco/prolog/roadmap/domain/Keyword.java
backend/src/main/resources/db/migration/prod/V2__create_table_keyword_reference.sql

- #1396
- Keyword 엔티티에 `List<String> urls` 추가
- flyway 스키마 V2 추가

Feature/#1396 키워드 엔티티에 추천 포스트 URL 필드 추가

---

backend/src/main/java/wooteco/prolog/studylog/application/PopularStudylogService.java
backend/src/test/java/wooteco/prolog/studylog/application/PopularStudylogServiceTest.java

- #1412 
인기학습로그 필터링 기능을 복구한다.
- close 1412

Fix/#1412 인기 학습로그 필터링 기능 복구

---

backend/src/main/java/wooteco/prolog/roadmap/domain/Keyword.java
backend/src/main/resources/db/migration/prod/V2__create_table_keyword_reference.sql

- #1396
-  flyway 스키마 추가
- 키워드 엔티티에 references 추가

Feature/1396 키워드 엔티티에 추천 포스트 컬럼 추가

---

frontend/src/components/Calendar/Calendar.tsx

fix: json() 코드 삭제 

---

.github/workflows/front-dev.yml
frontend/src/apis/comment.ts
frontend/src/apis/curriculum.ts
frontend/src/apis/keywords.ts
frontend/src/apis/levellogs.ts
frontend/src/apis/studylogs.ts

close #1451
프롤로그 임시 저장 API 호출 문제를 고쳐 글쓰기 기능이 정상 동작하도록 하였습니다.

Hotfix/1451 프롤로그 글쓰기 기능 핫픽스

---

frontend/src/components/Article/Article.style.tsx
frontend/src/components/Article/Article.tsx
frontend/src/components/NavBar/NavBar.tsx

Refactor/#1465 아티클 네비게이션 탭 활성화 및 링크 이동기능 추가

---

frontend/src/components/Article/Article.style.tsx
frontend/src/components/Article/Article.tsx
frontend/src/components/NavBar/NavBar.tsx

#1465 
아티클 네비게이션 및 링크 이동 기능 데브서버 확인 후 머지합니다.

Refactor/#1465 아티클 네비게이션 및 링크 이동 기능 

---

backend/build.gradle
backend/src/acceptanceTest/java/wooteco/prolog/fixtures/ArticleFixture.java
backend/src/main/java/wooteco/prolog/article/application/ArticleService.java
backend/src/main/java/wooteco/prolog/article/application/OgTagParser.java
backend/src/main/java/wooteco/prolog/article/domain/Article.java
backend/src/main/java/wooteco/prolog/article/ui/ArticleController.java
backend/src/main/java/wooteco/prolog/article/ui/ArticleResponse.java
backend/src/main/java/wooteco/prolog/article/ui/ArticleUrlRequest.java
backend/src/main/java/wooteco/prolog/article/ui/ArticleUrlResponse.java
backend/src/test/java/wooteco/prolog/article/application/ArticleServiceTest.java
backend/src/test/java/wooteco/prolog/article/application/OgTagParserTest.java
backend/src/test/java/wooteco/prolog/article/domain/ArticleTest.java

> close #1469 
> 입력받은 URL 로 부터 OG 태그를 파싱한다.
>

Url로부터 OG 태그를 파싱한다.

---

frontend/src/apis/articles.ts
frontend/src/hooks/Articles/useArticles.ts
frontend/src/mocks/handlers/articles.ts
frontend/src/models/Article.ts
frontend/src/pages/NewArticlePage/index.tsx

close #1482 
- [GET] /meta-og?url={url}

refactor/#1482 변경된 metaOg api 반영 및 타입 추가

---

backend/src/main/java/wooteco/prolog/article/application/ArticleService.java
backend/src/main/java/wooteco/prolog/article/domain/repository/ArticleRepository.java

아티클을 최신순으로 정렬한다.

---

frontend/src/apis/articles.ts

fix: meta og url 인자오류 수정

---

frontend/src/constants/message.ts
frontend/src/hooks/queries/article.ts
frontend/src/pages/NewArticlePage/index.tsx

아티클 추가 로직에 useMutation 적용
리다이렉트 시 아티클 get 데이터 자동 fetch 동작

refactor: 아티클 추가 로직에 useMutation 적용

---

frontend/src/components/Article/ArticleList.tsx

fix: useQuery 미적용 코드 적용

---

frontend/src/pages/NewArticlePage/index.tsx

> #1495 
meta og 관련 링크 입력 input에 enter key 눌렀을 시 새로고침 안되도록 수정
>

refactor: meta og 관련 링크 입력 input에 enter key 눌렀을 시 새로고침 안되도록 수정

---

backend/src/main/resources/application.yml

- #1500 
- flyway 옵션 false로 수정
(죄송합니다.)

Fix/#1500 flyway 설정 false로 수정

---

backend/src/main/resources/application.yml

- #1500 
- flyway 옵션 false로 수정
(죄송합니다.)

fix: flyway false로 변경

---

frontend/src/components/CreatableSelectBox/CreatableSelectBox.tsx
frontend/src/components/SearchBar/SearchBar.styles.tsx
frontend/src/components/SearchBar/SearchBar.tsx

 js > ts 마이그레이션

---

frontend/src/hooks/useValidParams.ts
frontend/src/hooks/useValidQueryString.ts
frontend/src/utils/arrayMutation.ts

- close #1515 
```tsx
const { id, amount } = useValidParams(['id', 'amount']); //  id: string , amount: string
```
```tsx
const { id } = useValidQueryString(['id']); // id: string | undefined
```

react router dom 유틸 훅 추가

---

.github/workflows/front-prod.yml

refactor: js ts 마이그레이션

---

frontend/src/apis/articles.ts
frontend/src/components/Article/Article.style.tsx
frontend/src/components/Article/Article.tsx
frontend/src/components/Article/ArticleBookmarkFIlter.tsx
frontend/src/components/Article/ArticleList.style.tsx
frontend/src/components/Article/ArticleList.tsx
frontend/src/components/Controls/SelectBox.tsx
frontend/src/components/Reaction/Scrap.styles.ts
frontend/src/components/Reaction/Scrap.tsx
frontend/src/hooks/queries/article.ts
frontend/src/mocks/db/articles-android.json
frontend/src/mocks/db/articles-backend.json
frontend/src/mocks/db/articles-frontend.json
frontend/src/mocks/db/articles.json
frontend/src/mocks/handlers/articles.ts
frontend/src/models/Article.ts
frontend/src/pages/ArticleListPage/index.tsx

#1540 
아티클 코스, 북마크 필터링 기능과 북마크 기능을 추가하였습니다.

feat: 아티클 북마크&필터링 기능 추가

---

backend/src/acceptanceTest/resources/wooteco/prolog/article.feature
backend/src/main/java/wooteco/prolog/article/domain/ArticleBookmark.java
backend/src/main/java/wooteco/prolog/article/domain/ArticleBookmarks.java
backend/src/main/java/wooteco/prolog/article/domain/ArticleLike.java
backend/src/main/java/wooteco/prolog/article/domain/ArticleLikes.java
backend/src/main/java/wooteco/prolog/article/domain/repository/ArticleRepository.java
backend/src/main/java/wooteco/prolog/article/ui/ArticleResponse.java
backend/src/test/java/wooteco/prolog/article/domain/ArticleBookmarksTest.java
backend/src/test/java/wooteco/prolog/article/domain/ArticleLikesTest.java

- #1557 
- 아티클 조회 시 좋아요 여부 반환
- 아티클 전체조회 테스트 수정

Feature/1557 아티클 조회 시 북마크 좋아요 반환

---

backend/src/main/java/wooteco/prolog/roadmap/application/KeywordService.java
backend/src/main/java/wooteco/prolog/roadmap/ui/EssayAnswerController.java
backend/src/main/java/wooteco/prolog/roadmap/ui/QuizController.java

- #1561 
quiz, essayAnswer 엔드 포인트 통일

refactor : 엔드포인트 통일

---

frontend/src/components/Article/Article.tsx

#1573 
북마크와 좋아요의 체크된 상태에서의 초기값을 변경합니다.

fix: 체크된 상태 초기값 변경

---

frontend/src/pages/ArticleListPage/index.tsx

#1575
기존 CREW였던 권한을 GUEST 제외로 변경하였습니다.

Refactor/#1575 아티클 글쓰기 role 변경

---

frontend/src/components/Article/Article.tsx

#1577 
좋아요, 북마크 버튼 클릭 시 아티클 조회수 요청을 보내지 않도록 한다

Fix/#1577 좋아요, 북마크 버튼 클릭 시 아티클 조회수 요청을 보내지 않도록 한다

---

frontend/src/pages/ArticleListPage/index.tsx

#1579 
모바일 버전일 때 아티클 글쓰기 버튼 디자인을 변경한다

Refactor/#1579 모바일 버전일 때 아티클 글쓰기 버튼 디자인을 변경한다

---

frontend/src/components/NavBar/NavBar.tsx
frontend/src/pages/StudylogListPage/index.tsx

- close #1588
navbar와 학습로그에 권한이 있는 사용자만 글쓰기 버튼이 활성화되도록 구현하였습니다.

Refactor/#1588 navbar&학습로그 권한 있는 사용자만 글쓰기 버튼 활성화

---

frontend/src/components/KeywordDetailSideSheet/KeywordDetailSideSheet.tsx
frontend/src/pages/RoadmapPage/index.tsx
frontend/src/pages/RoadmapPage/styles.tsx

게스트 회원은 로드맵 답변을 쓸 수 없다

---

frontend/src/components/Article/Article.tsx

비로그인일 때 좋아요와 북마크를 누르면 api를 보내는 것을 비활성화하였습니다.

Hotfix 좋아요, 북마크 비로그인시 api 비활성화

---

frontend/src/components/NavBar/NavBar.tsx

fix: 로그인 시 프로필 표시 하도록 수정

---

frontend/src/components/DropdownMenu/DropdownMenu.styles.ts

fix: 아이콘 Dom 구조 변경으로 인한 드롭다운 표시 에러 수정

fix: 아이콘 Dom 구조 변경으로 인한 드롭다운 표시 에러 수정

---

frontend/src/pages/RoadmapPage/components/Roadmap/SubKeyword.tsx

Safari에서 로드맵 퀴즈 progress가 표시되지 않는 오류를 수정

---

backend/src/documentation/adoc/quiz.adoc
backend/src/documentation/java/wooteco/prolog/docu/QuizDocumentation.java
backend/src/main/java/wooteco/prolog/roadmap/application/QuizService.java
backend/src/main/java/wooteco/prolog/roadmap/application/dto/CurriculumQuizResponse.java
backend/src/main/java/wooteco/prolog/roadmap/domain/repository/QuizRepository.java
backend/src/main/java/wooteco/prolog/roadmap/ui/QuizController.java
backend/src/test/java/wooteco/prolog/roadmap/repository/QuizRepositoryTest.java

- #1607
- 커리큘럼 별 퀴즈 조회 기능을 구현했습니다.

커리큘럼 별 퀴즈 API 생성

---

backend/src/main/java/wooteco/prolog/session/application/SessionMemberService.java
backend/src/main/java/wooteco/prolog/session/application/dto/SessionDepartmentMemberRequest.java
backend/src/main/java/wooteco/prolog/session/ui/SessionMemberController.java
backend/src/main/java/wooteco/prolog/studylog/application/PopularStudylogService.java
backend/src/test/java/wooteco/prolog/session/application/SessionMemberServiceTest.java

fix: Map.getObject 수정

---

backend/src/main/java/wooteco/prolog/member/domain/Part.java
backend/src/test/java/wooteco/prolog/member/domain/DepartmentTest.java

fix: error message

---

backend/src/main/resources/db/migration/prod/V10__fix_table_group_and_member.sql

fix: flyway-script v10

---

frontend/src/components/DropdownMenu/DropdownMenu.styles.ts
frontend/src/components/DropdownMenu/DropdownMenu.tsx
frontend/src/pages/EssayAnswerListPage/components/RoadmapFilter/RoadmapFilter.styles.ts
frontend/src/pages/EssayAnswerListPage/components/RoadmapFilter/RoadmapFilter.tsx
frontend/src/pages/EssayAnswerListPage/index.tsx

resolve #1388
|수정 전|수정 후|
|:-:|:-:|
|![image](https://github.com/woowacourse/prolog/assets/20203944/354bc3ca-5895-46ff-ba13-d86153abce6a)|![image](https://github.com/woowacourse/prolog/assets/20203944/595839b3-b470-41ad-a8aa-a6ef84e0fb61)|
* Dropdown의 위치가 올바르지 않게 표시되는 오류 수정

Dropdown의 위치가 올바르지 않게 되는 오류 수정
